import { describe, expect, it } from "vitest";
import { createLocalTableRow, mapMasterSpecificationSource, parseLocalTableRows, quoteLineEstimate, renderStructuredLifecycleTemplatePreview, serializeLocalTableRows, structuredLifecycleTemplatePreviews, tableRowsForOutput, validateStructuredLocalEdits } from "./lifecycle-structured-template-previews";

const source = mapMasterSpecificationSource({ opportunityId: "opportunity-id", opportunityNumber: "OPPORTUNITY-2026-0013", opportunityName: "Tracker <script>alert(1)</script>", customerId: "customer-id", customerName: "SAMPLE ONLY", specificationId: "specification-id", specificationNumber: "MASTER-2026-0001", versionId: "version-id", versionNumber: 1, changeSummary: "Initial intake", savedAt: "2026-10-05T18:37:27.589Z", specificationData: { requirementSummary: "24V tracker", powerAndUnits: "12/24V nominal input", interfaces: "CAN requested", connectivityAndGnss: "LTE/GNSS requested", environmentAndIp: "", volumes: "20 pilot units", requestedStandards: "", workstreams: ["HARDWARE", "FIRMWARE", "MECHANICAL"] } });
const quoteRows = serializeLocalTableRows([{ id: "quote-1", line: "1", description: "Prototype <img src=x onerror=alert(1)>", quantity: "20", unitPrice: "0", currency: "SEK", leadTime: "TBC" }]);
const tierRows = serializeLocalTableRows([{ id: "tier-1", minQuantity: "1", maxQuantity: "20", unitPrice: "0" }, { id: "tier-2", minQuantity: "21", maxQuantity: "100", unitPrice: "TBC" }]);
const bomRows = serializeLocalTableRows([{ id: "bom-1", itemNumber: "1", mpn: "TBC", manufacturer: "TBC", description: "Local board", package: "TBC", quantity: "0", leadTime: "TBC", unitCost: "0", currency: "SEK", aecqEvidence: "TBC" }]);

describe("structured lifecycle template previews", () => {
  it("defines six distinct safe document schemas with typed local tables", () => { expect(structuredLifecycleTemplatePreviews.map((template) => template.kind)).toEqual(["SOR", "CONTRACT_REVIEW", "PRS", "NDA", "COMMERCIAL_QUOTATION", "BOM_COST_TRACKER"]); expect(structuredLifecycleTemplatePreviews.find((item) => item.kind === "COMMERCIAL_QUOTATION")?.editableFields.filter((field) => field.kind === "table").map((field) => field.key)).toEqual(["QUOTE_LINE_ROWS", "VOLUME_TIER_ROWS"]); expect(structuredLifecycleTemplatePreviews.find((item) => item.kind === "BOM_COST_TRACKER")?.editableFields.find((field) => field.key === "BOM_COST_ROWS")?.kind).toBe("table"); });
  it("uses stable row IDs and preserves local table rows for output", () => { const row = createLocalTableRow("QUOTE_LINE_ROWS", "stable-row"); expect(row.id).toBe("stable-row"); const rows = parseLocalTableRows("QUOTE_LINE_ROWS", quoteRows); expect(rows[0]?.id).toBe("quote-1"); expect(tableRowsForOutput("QUOTE_LINE_ROWS", quoteRows)[0]).toEqual(["1", "Prototype <img src=x onerror=alert(1)>", "20", "0", "SEK", "TBC"]); });
  it("keeps explicit zero distinct from unknown and makes estimates provisional", () => { const rows = parseLocalTableRows("QUOTE_LINE_ROWS", quoteRows); expect(quoteLineEstimate(rows[0] as any)).toBe("0"); expect(quoteLineEstimate({ ...(rows[0] as any), unitPrice: "" })).toBe("TBC"); expect(renderStructuredLifecycleTemplatePreview("COMMERCIAL_QUOTATION", source, { QUOTE_LINE_ROWS: quoteRows, VOLUME_TIER_ROWS: tierRows, NRE_AMOUNT: "TBC", TOOLING_AMOUNT: "TBC", PAYMENT_TERMS: "TBC", LEAD_TIME: "TBC" }).content).toContain("Prototype <img src=x onerror=alert(1)>"); });
  it("rejects negative, non-finite, reversed and overlapping table quantities or costs", () => { expect(() => validateStructuredLocalEdits("COMMERCIAL_QUOTATION", { QUOTE_LINE_ROWS: serializeLocalTableRows([{ id: "x", line: "1", description: "x", quantity: "-1", unitPrice: "TBC", currency: "", leadTime: "" }]), VOLUME_TIER_ROWS: "" })).toThrow("Quote quantity"); expect(() => validateStructuredLocalEdits("BOM_COST_TRACKER", { BOM_COST_ROWS: serializeLocalTableRows([{ id: "x", itemNumber: "", mpn: "", manufacturer: "", description: "", package: "", quantity: "Infinity", leadTime: "", unitCost: "", currency: "", aecqEvidence: "" }]) })).toThrow("BOM quantity"); expect(() => validateStructuredLocalEdits("COMMERCIAL_QUOTATION", { VOLUME_TIER_ROWS: serializeLocalTableRows([{ id: "a", minQuantity: "10", maxQuantity: "1", unitPrice: "TBC" }]) })).toThrow("minimum"); expect(() => validateStructuredLocalEdits("COMMERCIAL_QUOTATION", { VOLUME_TIER_ROWS: serializeLocalTableRows([{ id: "a", minQuantity: "1", maxQuantity: "10", unitPrice: "TBC" }, { id: "b", minQuantity: "10", maxQuantity: "20", unitPrice: "TBC" }]) })).toThrow("overlap"); });
  it("accepts unknown values and valid non-overlapping tiers", () => { expect(() => validateStructuredLocalEdits("COMMERCIAL_QUOTATION", { QUOTE_LINE_ROWS: quoteRows, VOLUME_TIER_ROWS: tierRows, NRE_AMOUNT: "0", TOOLING_AMOUNT: "TBC" })).not.toThrow(); expect(() => validateStructuredLocalEdits("BOM_COST_TRACKER", { BOM_COST_ROWS: bomRows, LOCAL_COST_TOTAL: "TBC" })).not.toThrow(); });
  it("renders table values once and treats injected markup as literal text", () => { const content = renderStructuredLifecycleTemplatePreview("BOM_COST_TRACKER", source, { BOM_COST_ROWS: serializeLocalTableRows([{ id: "x", itemNumber: "1", mpn: "<script>alert(1)</script>", manufacturer: "TBC", description: "TBC", package: "TBC", quantity: "TBC", leadTime: "TBC", unitCost: "TBC", currency: "TBC", aecqEvidence: "TBC" }]), COST_RISK_NOTES: "TBC", LOCAL_COST_TOTAL: "TBC" }).content; expect(content).toContain("<script>alert(1)</script>"); expect(content).not.toContain("<script>alert(1)</script>OPPORTUNITY-2026-0013"); });
  it("maps authoritative source values without inventing technical or approval data", () => { expect(source.sourceFields.POWER_AND_UNITS).toBe("12/24V nominal input"); expect(source.sourceFields.INTERFACES).toBe("CAN requested"); expect(source.sourceFields.CONNECTIVITY_AND_GNSS).toBe("LTE/GNSS requested"); expect(source.sourceFields.VOLUMES).toBe("20 pilot units"); expect(source.sourceFields.ENVIRONMENT_AND_IP).toBe("TBC"); expect(renderStructuredLifecycleTemplatePreview("CONTRACT_REVIEW", source).content).toContain("NOT APPROVED / TBC"); });
});
