import { renderLifecycleDocument, type DocumentTemplate } from "@/lib/lifecycle-document-renderer";

export type StructuredLifecycleTemplateKind = "SOR" | "CONTRACT_REVIEW" | "PRS" | "NDA" | "COMMERCIAL_QUOTATION" | "BOM_COST_TRACKER" | "DFMEA" | "MANUFACTURING_CONTROL_PLAN" | "DVPR";
export type StructuredTemplateSource = { opportunityId: string; opportunityNumber: string; opportunityName: string; customerId: string; customerName: string; specificationId: string; specificationNumber: string; versionId: string; versionNumber: number; changeSummary: string | null; savedAt: string | null; project: { id: string; name: string; code: string | null } | null; sourceFields: Record<string, string | null> };
export type EditableField = { key: string; label: string; kind: "text" | "textarea" | "number" | "table"; group: string; placeholder?: string };
export type StructuredLifecycleTemplatePreview = { kind: StructuredLifecycleTemplateKind; label: string; description: string; sourceFields: string[]; editableFields: EditableField[]; template: DocumentTemplate; fields: Record<string, string | null> };
export type QuoteLineRow = { id: string; line: string; description: string; quantity: string; unitPrice: string; currency: string; leadTime: string };
export type VolumeTierRow = { id: string; minQuantity: string; maxQuantity: string; unitPrice: string };
export type BomCostRow = { id: string; itemNumber: string; mpn: string; manufacturer: string; description: string; package: string; quantity: string; leadTime: string; unitCost: string; currency: string; aecqEvidence: string };
export type DfmeaRow = { id: string; function: string; failureMode: string; effect: string; cause: string; preventionControl: string; detectionControl: string; severity: string; occurrence: string; detection: string; owner: string; action: string };
export type ControlPlanRow = { id: string; processStep: string; characteristic: string; specification: string; method: string; equipment: string; sampleFrequency: string; reactionPlan: string; owner: string };
export type DvprRow = { id: string; test: string; applicability: string; sampleCount: string; acceptanceCriteria: string; result: string; evidence: string; standardsReference: string };
export type LocalTableRow = QuoteLineRow | VolumeTierRow | BomCostRow | DfmeaRow | ControlPlanRow | DvprRow;
export type LocalTableKey = "QUOTE_LINE_ROWS" | "VOLUME_TIER_ROWS" | "BOM_COST_ROWS" | "DFMEA_ROWS" | "CONTROL_PLAN_ROWS" | "DVPR_ROWS";

const localRevision = "local-preview-only";
const tbc = "TBC";
const coreFields = { PROJECT_CODE: tbc, PROJECT_NAME: tbc, PROJECT_REVISION: tbc, CUSTOMER_NAME: tbc, MASTER_SPECIFICATION: tbc, SOURCE_DOCUMENT: tbc, REQUIREMENT_SUMMARY: tbc, POWER_AND_UNITS: tbc, INTERFACES: tbc, CONNECTIVITY_AND_GNSS: tbc, ENVIRONMENT_AND_IP: tbc, VOLUMES: tbc, REQUESTED_STANDARDS: tbc, WORKSTREAMS: tbc };

export const structuredLifecycleTemplatePreviews: StructuredLifecycleTemplatePreview[] = [
  { kind: "SOR", label: "Statement of Requirements", description: "Source requirements are pinned; local scope and commercial review notes are deliberately unsaved.", sourceFields: ["PROJECT_CODE", "PROJECT_NAME", "PROJECT_REVISION", "CUSTOMER_NAME", "REQUIREMENT_SUMMARY", "POWER_AND_UNITS", "INTERFACES", "CONNECTIVITY_AND_GNSS", "VOLUMES"], editableFields: [{ key: "OEM_REQUIREMENT_ROWS", label: "OEM requirement rows", kind: "textarea", group: "OEM requirements", placeholder: "Requirement ID | requested outcome | source / note" }, { key: "SCOPE_STATEMENT", label: "Scope statement", kind: "textarea", group: "Scope and acceptance" }, { key: "ACCEPTANCE_CRITERIA", label: "Acceptance criteria", kind: "textarea", group: "Scope and acceptance" }, { key: "CAN_TELEMETRY_NOTES", label: "CAN / telemetry review notes", kind: "textarea", group: "Connectivity and telemetry" }, { key: "PILOT_ROLLOUT_NOTES", label: "Pilot and rollout notes", kind: "textarea", group: "Pilot and rollout" }, { key: "COMMERCIAL_SLA_WARRANTY_DELIVERY", label: "SLA, warranty and delivery notes", kind: "textarea", group: "Commercial review" }], template: { templateKey: "SOR", version: 1, title: "Statement of Requirements", content: "STATEMENT OF REQUIREMENTS\n\nProject: {{PROJECT_CODE}} — {{PROJECT_NAME}}\nMaster Specification: {{MASTER_SPECIFICATION}}\nRevision: {{PROJECT_REVISION}}\nCustomer: {{CUSTOMER_NAME}}\n\n1. OEM requirements\n{{OEM_REQUIREMENT_ROWS}}\n\n2. Connectivity and telemetry\n| Source field | Requested value |\n| --- | --- |\n| Interfaces | {{INTERFACES}} |\n| Connectivity / GNSS | {{CONNECTIVITY_AND_GNSS}} |\n\nLocal CAN / telemetry review notes\n{{CAN_TELEMETRY_NOTES}}\n\n3. Pilot and rollout\nRequested volume: {{VOLUMES}}\n{{PILOT_ROLLOUT_NOTES}}\n\n4. Commercial review\n{{COMMERCIAL_SLA_WARRANTY_DELIVERY}}\n\n5. Scope\n{{SCOPE_STATEMENT}}\n\n6. Acceptance criteria\n{{ACCEPTANCE_CRITERIA}}" }, fields: { ...coreFields, OEM_REQUIREMENT_ROWS: tbc, SCOPE_STATEMENT: tbc, ACCEPTANCE_CRITERIA: tbc, CAN_TELEMETRY_NOTES: tbc, PILOT_ROLLOUT_NOTES: tbc, COMMERCIAL_SLA_WARRANTY_DELIVERY: tbc } },
  { kind: "CONTRACT_REVIEW", label: "Contract Review", description: "All feasibility and approval positions begin as NOT APPROVED / TBC; local review inputs cannot create a verdict.", sourceFields: ["PROJECT_CODE", "CUSTOMER_NAME", "MASTER_SPECIFICATION", "SOURCE_DOCUMENT", "REQUIREMENT_SUMMARY", "WORKSTREAMS", "VOLUMES"], editableFields: [{ key: "HARDWARE_FEASIBILITY", label: "Hardware feasibility evidence / risk / owner", kind: "textarea", group: "Workstream feasibility" }, { key: "FIRMWARE_FEASIBILITY", label: "Firmware feasibility evidence / risk / owner", kind: "textarea", group: "Workstream feasibility" }, { key: "MECHANICAL_FEASIBILITY", label: "Mechanical feasibility evidence / risk / owner", kind: "textarea", group: "Workstream feasibility" }, { key: "COMMERCIAL_EVIDENCE", label: "Commercial evidence and risk", kind: "textarea", group: "Commercial review" }, { key: "OWNER_AND_ACTION", label: "Local owner and next action", kind: "textarea", group: "Commercial review" }, { key: "LOCAL_DECISION_NOTE", label: "Local decision note", kind: "textarea", group: "Decision record" }], template: { templateKey: "CONTRACT-REVIEW", version: 1, title: "Contract Review", content: "CONTRACT REVIEW\n\n| Review item | Verified source | Local position |\n| --- | --- | --- |\n| Opportunity | {{PROJECT_CODE}} | NOT APPROVED / TBC |\n| Customer | {{CUSTOMER_NAME}} | NOT APPROVED / TBC |\n| Master Specification | {{MASTER_SPECIFICATION}} | NOT APPROVED / TBC |\n| Source record | {{SOURCE_DOCUMENT}} | NOT APPROVED / TBC |\n\nRequirement summary\n{{REQUIREMENT_SUMMARY}}\n\n| Workstream / department | Requested source | Local evidence, risk and owner | Approval |\n| --- | --- | --- | --- |\n| Hardware | {{WORKSTREAMS}} | {{HARDWARE_FEASIBILITY}} | NOT APPROVED / TBC |\n| Firmware | {{WORKSTREAMS}} | {{FIRMWARE_FEASIBILITY}} | NOT APPROVED / TBC |\n| Mechanical | {{WORKSTREAMS}} | {{MECHANICAL_FEASIBILITY}} | NOT APPROVED / TBC |\n\nCommercial evidence and risk\n{{COMMERCIAL_EVIDENCE}}\n\nLocal owner and next action\n{{OWNER_AND_ACTION}}\n\nLocal decision note\n{{LOCAL_DECISION_NOTE}}\n\nCustomer authorization: NOT APPROVED / TBC (not inferred)." }, fields: { ...coreFields, HARDWARE_FEASIBILITY: tbc, FIRMWARE_FEASIBILITY: tbc, MECHANICAL_FEASIBILITY: tbc, COMMERCIAL_EVIDENCE: tbc, OWNER_AND_ACTION: tbc, LOCAL_DECISION_NOTE: tbc } },
  { kind: "PRS", label: "Product Requirements Specification", description: "Requested technical values come from the pinned Master Specification; components, standards and unspecified constraints remain TBC.", sourceFields: ["PROJECT_CODE", "PROJECT_NAME", "PROJECT_REVISION", "POWER_AND_UNITS", "INTERFACES", "CONNECTIVITY_AND_GNSS", "ENVIRONMENT_AND_IP", "REQUESTED_STANDARDS", "VOLUMES"], editableFields: [{ key: "POWER_REQUIREMENT", label: "Power requirement", kind: "textarea", group: "Power and electrical" }, { key: "INTERFACE_REQUIREMENT", label: "Interface requirement", kind: "textarea", group: "Interfaces and connectivity" }, { key: "CONNECTIVITY_REQUIREMENT", label: "Connectivity / GNSS requirement", kind: "textarea", group: "Interfaces and connectivity" }, { key: "MECHANICAL_REQUIREMENT", label: "Mechanical / environmental requirement", kind: "textarea", group: "Mechanical and environmental" }, { key: "FIRMWARE_REQUIREMENT", label: "Firmware requirement", kind: "textarea", group: "Firmware and verification" }, { key: "VERIFICATION_METHOD", label: "Local verification proposal", kind: "text", group: "Firmware and verification" }], template: { templateKey: "PRS", version: 1, title: "Product Requirements Specification", content: "PRODUCT REQUIREMENTS SPECIFICATION\n\nProject: {{PROJECT_CODE}} — {{PROJECT_NAME}}\nMaster Specification: {{MASTER_SPECIFICATION}}\nRevision: {{PROJECT_REVISION}}\n\n| ID | Requirement area | Requested source value | Local requirement / verification proposal | Status |\n| --- | --- | --- | --- | --- |\n| PRS-001 | Power | {{POWER_AND_UNITS}} | {{POWER_REQUIREMENT}} | TBC |\n| PRS-002 | Interfaces | {{INTERFACES}} | {{INTERFACE_REQUIREMENT}} | TBC |\n| PRS-003 | Connectivity / GNSS | {{CONNECTIVITY_AND_GNSS}} | {{CONNECTIVITY_REQUIREMENT}} | TBC |\n| PRS-004 | Mechanical / environmental | {{ENVIRONMENT_AND_IP}} | {{MECHANICAL_REQUIREMENT}} | TBC |\n| PRS-005 | Firmware | TBC | {{FIRMWARE_REQUIREMENT}} · {{VERIFICATION_METHOD}} | TBC |\n| PRS-006 | Components | TBC | TBC | TBC |\n| PRS-007 | Standards | {{REQUESTED_STANDARDS}} | TBC | TBC |\n\nRequested pilot / rollout volume: {{VOLUMES}}\n\nNo component, IP rating, controller, standard, compliance or approval is inferred by this local preview." }, fields: { ...coreFields, POWER_REQUIREMENT: tbc, INTERFACE_REQUIREMENT: tbc, CONNECTIVITY_REQUIREMENT: tbc, MECHANICAL_REQUIREMENT: tbc, FIRMWARE_REQUIREMENT: tbc, VERIFICATION_METHOD: tbc } },
  { kind: "NDA", label: "NDA review", description: "A local clause checklist only. Confidential scope, obligations, IP and governing law remain UNCONFIRMED / TBC until a legal approval contract is accepted.", sourceFields: ["PROJECT_CODE", "CUSTOMER_NAME", "MASTER_SPECIFICATION", "REQUIREMENT_SUMMARY"], editableFields: [{ key: "CONFIDENTIAL_SCOPE", label: "Confidential scope", kind: "textarea", group: "Confidential information" }, { key: "OBLIGATIONS", label: "Receiving-party obligations", kind: "textarea", group: "Obligations" }, { key: "IP_POSITION", label: "Intellectual property position", kind: "textarea", group: "Intellectual property" }, { key: "GOVERNING_LAW", label: "Governing law / jurisdiction", kind: "textarea", group: "Governing law" }], template: { templateKey: "NDA-REVIEW", version: 1, title: "NDA Review", content: "NDA REVIEW — LOCAL PREVIEW ONLY\n\nOpportunity: {{PROJECT_CODE}}\nCustomer: {{CUSTOMER_NAME}}\nMaster Specification: {{MASTER_SPECIFICATION}}\n\n| Clause section | Local review input | State |\n| --- | --- | --- |\n| Confidential scope | {{CONFIDENTIAL_SCOPE}} | UNCONFIRMED / TBC |\n| Obligations | {{OBLIGATIONS}} | UNCONFIRMED / TBC |\n| Intellectual property | {{IP_POSITION}} | UNCONFIRMED / TBC |\n| Governing law | {{GOVERNING_LAW}} | UNCONFIRMED / TBC |\n\nNo legal language, execution, approval or authorization is asserted by this local preview." }, fields: { ...coreFields, CONFIDENTIAL_SCOPE: tbc, OBLIGATIONS: tbc, IP_POSITION: tbc, GOVERNING_LAW: tbc } },
  { kind: "COMMERCIAL_QUOTATION", label: "Commercial quotation", description: "A local quotation worksheet. Prices, terms and commitments remain TBC unless an approved commercial source is available; zero is never substituted for an unknown price.", sourceFields: ["PROJECT_CODE", "CUSTOMER_NAME", "MASTER_SPECIFICATION", "VOLUMES", "REQUIREMENT_SUMMARY"], editableFields: [{ key: "QUOTE_LINE_ROWS", label: "Quote line rows", kind: "table", group: "Quote lines" }, { key: "VOLUME_TIER_ROWS", label: "Volume-tier rows", kind: "table", group: "Volume tiers" }, { key: "NRE_AMOUNT", label: "NRE amount", kind: "number", group: "Commercial terms", placeholder: "TBC" }, { key: "TOOLING_AMOUNT", label: "Tooling amount", kind: "number", group: "Commercial terms", placeholder: "TBC" }, { key: "PAYMENT_TERMS", label: "Payment terms", kind: "textarea", group: "Commercial terms" }, { key: "LEAD_TIME", label: "Lead time", kind: "text", group: "Commercial terms" }], template: { templateKey: "COMMERCIAL-QUOTATION", version: 1, title: "Commercial Quotation Review", content: "COMMERCIAL QUOTATION — LOCAL PREVIEW ONLY\n\nOpportunity: {{PROJECT_CODE}}\nCustomer: {{CUSTOMER_NAME}}\nMaster Specification: {{MASTER_SPECIFICATION}}\nRequested volume: {{VOLUMES}}\n\nQuote lines (local / provisional)\n{{QUOTE_LINE_ROWS}}\n\nVolume tiers (local / provisional)\n{{VOLUME_TIER_ROWS}}\n\n| Commercial field | Local value | State |\n| --- | --- | --- |\n| NRE | {{NRE_AMOUNT}} | TBC / not approved |\n| Tooling | {{TOOLING_AMOUNT}} | TBC / not approved |\n| Payment terms | {{PAYMENT_TERMS}} | TBC / not approved |\n| Lead time | {{LEAD_TIME}} | TBC / not approved |\n\nUnknown commercial values remain TBC, not zero. This does not create a customer offer, authorization or commitment." }, fields: { ...coreFields, QUOTE_LINE_ROWS: tbc, VOLUME_TIER_ROWS: tbc, NRE_AMOUNT: tbc, TOOLING_AMOUNT: tbc, PAYMENT_TERMS: tbc, LEAD_TIME: tbc } },
  { kind: "BOM_COST_TRACKER", label: "BOM review", description: "Existing saved project BOMs remain the authority. Local scratch rows are optional, unsaved review notes only and never become a BOM, inventory position, or sourcing record.", sourceFields: ["PROJECT_CODE", "MASTER_SPECIFICATION", "POWER_AND_UNITS", "INTERFACES", "VOLUMES"], editableFields: [{ key: "BOM_COST_ROWS", label: "Optional local scratch rows", kind: "table", group: "Unsaved review scratchpad" }, { key: "COST_RISK_NOTES", label: "Cost and supply risk notes", kind: "textarea", group: "Unsaved review scratchpad" }, { key: "LOCAL_COST_TOTAL", label: "Local estimated total", kind: "number", group: "Unsaved review scratchpad", placeholder: "TBC" }], template: { templateKey: "BOM-COST-TRACKER", version: 1, title: "BOM Review", content: "BOM REVIEW — LOCAL PREVIEW ONLY\n\nOpportunity: {{PROJECT_CODE}}\nMaster Specification: {{MASTER_SPECIFICATION}}\nRequested power / interfaces: {{POWER_AND_UNITS}} / {{INTERFACES}}\nRequested volume: {{VOLUMES}}\n\nOptional unsaved local scratch rows\n{{BOM_COST_ROWS}}\n\nLocal estimated total: {{LOCAL_COST_TOTAL}}\n\nCost and supply risk notes\n{{COST_RISK_NOTES}}\n\nThe project BOM tool and its saved revision remain the only BOM authority. Components, prices, availability and grades remain TBC unless explicitly entered as unsaved local review. This preview cannot create a BOM, inventory movement, or sourcing approval." }, fields: { ...coreFields, BOM_COST_ROWS: tbc, COST_RISK_NOTES: tbc, LOCAL_COST_TOTAL: tbc } },
  { kind: "DFMEA", label: "DFMEA", description: "A local design-risk review only. Failure modes, controls, owners, actions, and risk ratings remain unresolved until a governed engineering review is accepted.", sourceFields: ["PROJECT_CODE", "MASTER_SPECIFICATION", "REQUIREMENT_SUMMARY", "WORKSTREAMS", "POWER_AND_UNITS", "INTERFACES"], editableFields: [{ key: "DFMEA_ROWS", label: "DFMEA rows", kind: "table", group: "Design risk analysis" }, { key: "DFMEA_REVIEW_NOTE", label: "Local review note", kind: "textarea", group: "Design risk analysis" }], template: { templateKey: "DFMEA", version: 1, title: "Design Failure Mode and Effects Analysis", content: "DFMEA — LOCAL PREVIEW ONLY\n\nOpportunity: {{PROJECT_CODE}}\nMaster Specification: {{MASTER_SPECIFICATION}}\nWorkstreams: {{WORKSTREAMS}}\nRequirement summary: {{REQUIREMENT_SUMMARY}}\n\nLocal DFMEA rows\n{{DFMEA_ROWS}}\n\nLocal review note\n{{DFMEA_REVIEW_NOTE}}\n\nRisk ratings and actions are unsaved local review inputs. No engineering sign-off, risk acceptance, or release is asserted." }, fields: { ...coreFields, DFMEA_ROWS: tbc, DFMEA_REVIEW_NOTE: tbc } },
  { kind: "MANUFACTURING_CONTROL_PLAN", label: "Manufacturing Control Plan", description: "A local process-control review. Process parameters, equipment, sampling, reaction plans, owners, and approvals remain TBC unless verified in controlled manufacturing records.", sourceFields: ["PROJECT_CODE", "MASTER_SPECIFICATION", "WORKSTREAMS", "REQUIREMENT_SUMMARY", "VOLUMES"], editableFields: [{ key: "CONTROL_PLAN_ROWS", label: "Control-plan rows", kind: "table", group: "Process controls" }, { key: "CONTROL_PLAN_NOTE", label: "Local control-plan note", kind: "textarea", group: "Process controls" }], template: { templateKey: "MANUFACTURING-CONTROL-PLAN", version: 1, title: "Manufacturing Control Plan", content: "MANUFACTURING CONTROL PLAN — LOCAL PREVIEW ONLY\n\nOpportunity: {{PROJECT_CODE}}\nMaster Specification: {{MASTER_SPECIFICATION}}\nWorkstreams: {{WORKSTREAMS}}\nRequested volume: {{VOLUMES}}\n\nLocal control-plan rows\n{{CONTROL_PLAN_ROWS}}\n\nLocal control-plan note\n{{CONTROL_PLAN_NOTE}}\n\nNo process parameter, SMT profile, equipment qualification, sampling approval, or production release is inferred." }, fields: { ...coreFields, CONTROL_PLAN_ROWS: tbc, CONTROL_PLAN_NOTE: tbc } },
  { kind: "DVPR", label: "DVP&R", description: "A local design-verification plan and report review. Test applicability, sample counts, criteria, results, evidence, standards references, and sign-offs remain unverified unless governed source records establish them.", sourceFields: ["PROJECT_CODE", "MASTER_SPECIFICATION", "REQUIREMENT_SUMMARY", "WORKSTREAMS", "REQUESTED_STANDARDS", "VOLUMES"], editableFields: [{ key: "DVPR_ROWS", label: "DVP&R rows", kind: "table", group: "Verification planning" }, { key: "DVPR_REVIEW_NOTE", label: "Local verification note", kind: "textarea", group: "Verification planning" }], template: { templateKey: "DVPR", version: 1, title: "Design Verification Plan and Report", content: "DVP&R — LOCAL PREVIEW ONLY\n\nOpportunity: {{PROJECT_CODE}}\nMaster Specification: {{MASTER_SPECIFICATION}}\nWorkstreams: {{WORKSTREAMS}}\nRequested standards: {{REQUESTED_STANDARDS}}\n\nLocal DVP&R rows\n{{DVPR_ROWS}}\n\nLocal verification note\n{{DVPR_REVIEW_NOTE}}\n\nA standards reference is a request only: it does not establish compliance, approval, a completed test, a pass result, or sign-off." }, fields: { ...coreFields, DVPR_ROWS: tbc, DVPR_REVIEW_NOTE: tbc } },
];

function text(value: unknown) { return typeof value === "number" && Number.isFinite(value) ? String(value) : typeof value === "string" && value.trim() ? value.trim() : tbc; }
function workstreams(value: unknown) { return Array.isArray(value) && value.every((item) => typeof item === "string" && item.trim()) && value.length ? value.join(", ") : tbc; }
const tableKeys: LocalTableKey[] = ["QUOTE_LINE_ROWS", "VOLUME_TIER_ROWS", "BOM_COST_ROWS", "DFMEA_ROWS", "CONTROL_PLAN_ROWS", "DVPR_ROWS"];
const unknown = (value: string) => !value.trim() || value.trim() === tbc;
const numeric = (value: string, label: string) => { if (unknown(value)) return; if (!/^\d+(?:\.\d{1,2})?$/.test(value.trim()) || !Number.isFinite(Number(value)) || Number(value) < 0) throw new Error(`${label} must be a non-negative finite number or TBC.`); };
export function createLocalTableRow(key: LocalTableKey, id: string): LocalTableRow { if (!id.trim()) throw new Error("Local row ID is required."); if (key === "QUOTE_LINE_ROWS") return { id, line: "", description: "", quantity: "", unitPrice: "", currency: "", leadTime: "" }; if (key === "VOLUME_TIER_ROWS") return { id, minQuantity: "", maxQuantity: "", unitPrice: "" }; if (key === "DFMEA_ROWS") return { id, function: "", failureMode: "", effect: "", cause: "", preventionControl: "", detectionControl: "", severity: "", occurrence: "", detection: "", owner: "", action: "" }; if (key === "CONTROL_PLAN_ROWS") return { id, processStep: "", characteristic: "", specification: "", method: "", equipment: "", sampleFrequency: "", reactionPlan: "", owner: "" }; if (key === "DVPR_ROWS") return { id, test: "", applicability: "", sampleCount: "", acceptanceCriteria: "", result: "", evidence: "", standardsReference: "" }; return { id, itemNumber: "", mpn: "", manufacturer: "", description: "", package: "", quantity: "", leadTime: "", unitCost: "", currency: "", aecqEvidence: "" }; }
export function dfmeaRpn(row: DfmeaRow) { const ratings = [row.severity, row.occurrence, row.detection]; return ratings.every((value) => /^([1-9]|10)$/.test(value.trim())) ? String(Number(row.severity) * Number(row.occurrence) * Number(row.detection)) : tbc; }
export function parseLocalTableRows(key: LocalTableKey, value: string | null | undefined): LocalTableRow[] { if (!value || value === tbc) return []; try { const parsed: unknown = JSON.parse(value); if (!Array.isArray(parsed)) return []; return parsed.filter((row): row is LocalTableRow => Boolean(row && typeof row === "object" && typeof (row as { id?: unknown }).id === "string")); } catch { return []; } }
export function serializeLocalTableRows(rows: LocalTableRow[]) { return JSON.stringify(rows); }
function rowDisplay(value: string) { return unknown(value) ? tbc : value.trim(); }
export type TableValidationIssue = { rowId: string; field: string; message: string };
const numericIssue = (rowId: string, field: string, value: string, label: string): TableValidationIssue | null => unknown(value) || (/^\d+(?:\.\d{1,2})?$/.test(value.trim()) && Number.isFinite(Number(value)) && Number(value) >= 0) ? null : { rowId, field, message: `${label} must be a non-negative finite number or TBC.` };
export function validateLocalTableRows(key: LocalTableKey, value: string | null | undefined): TableValidationIssue[] {
  const rows = parseLocalTableRows(key, value); const issues: TableValidationIssue[] = [];
  if (key === "QUOTE_LINE_ROWS") for (const row of rows as QuoteLineRow[]) { const quantity = numericIssue(row.id, "quantity", row.quantity, "Quantity"); const price = numericIssue(row.id, "unitPrice", row.unitPrice, "Unit price"); if (quantity) issues.push(quantity); if (price) issues.push(price); }
  if (key === "BOM_COST_ROWS") for (const row of rows as BomCostRow[]) { const quantity = numericIssue(row.id, "quantity", row.quantity, "Quantity"); const cost = numericIssue(row.id, "unitCost", row.unitCost, "Unit cost"); if (quantity) issues.push(quantity); if (cost) issues.push(cost); }
  if (key === "DFMEA_ROWS") for (const row of rows as DfmeaRow[]) for (const [field, label] of [["severity", "Severity"], ["occurrence", "Occurrence"], ["detection", "Detection"]] as const) { const rating = row[field]; if (!unknown(rating) && !/^([1-9]|10)$/.test(rating.trim())) issues.push({ rowId: row.id, field, message: `${label} must be an integer from 1 to 10 or TBC.` }); }
  if (key === "DVPR_ROWS") for (const row of rows as DvprRow[]) { const sampleCount = numericIssue(row.id, "sampleCount", row.sampleCount, "Sample count"); if (sampleCount) issues.push(sampleCount); }
  if (key === "VOLUME_TIER_ROWS") { const tiers = rows as VolumeTierRow[]; for (const tier of tiers) { for (const [field, label] of [["minQuantity", "Minimum quantity"], ["maxQuantity", "Maximum quantity"], ["unitPrice", "Unit price"]] as const) { const issue = numericIssue(tier.id, field, tier[field], label); if (issue) issues.push(issue); } if (!unknown(tier.minQuantity) && !unknown(tier.maxQuantity) && Number(tier.minQuantity) > Number(tier.maxQuantity)) issues.push({ rowId: tier.id, field: "maxQuantity", message: "Maximum quantity cannot be below minimum quantity." }); }
    const complete = tiers.filter((tier) => !unknown(tier.minQuantity) && !unknown(tier.maxQuantity)).sort((a, b) => Number(a.minQuantity) - Number(b.minQuantity));
    for (let index = 1; index < complete.length; index += 1) if (Number(complete[index - 1].maxQuantity) >= Number(complete[index].minQuantity)) { issues.push({ rowId: complete[index - 1].id, field: "maxQuantity", message: "This tier overlaps another tier." }); issues.push({ rowId: complete[index].id, field: "minQuantity", message: "This tier overlaps another tier." }); }
  }
  return issues;
}
export function tableRowsForOutput(key: LocalTableKey, value: string | null | undefined): string[][] {
  if (key === "QUOTE_LINE_ROWS") return (parseLocalTableRows(key, value) as QuoteLineRow[]).map((row) => [rowDisplay(row.line), rowDisplay(row.description), rowDisplay(row.quantity), rowDisplay(row.unitPrice), rowDisplay(row.currency), rowDisplay(row.leadTime)]);
  if (key === "VOLUME_TIER_ROWS") return (parseLocalTableRows(key, value) as VolumeTierRow[]).map((row) => [rowDisplay(row.minQuantity), rowDisplay(row.maxQuantity), rowDisplay(row.unitPrice)]);
  if (key === "DFMEA_ROWS") return (parseLocalTableRows(key, value) as DfmeaRow[]).map((row) => [rowDisplay(row.function), rowDisplay(row.failureMode), rowDisplay(row.effect), rowDisplay(row.cause), rowDisplay(row.preventionControl), rowDisplay(row.detectionControl), rowDisplay(row.severity), rowDisplay(row.occurrence), rowDisplay(row.detection), dfmeaRpn(row), rowDisplay(row.owner), rowDisplay(row.action)]);
  if (key === "CONTROL_PLAN_ROWS") return (parseLocalTableRows(key, value) as ControlPlanRow[]).map((row) => [rowDisplay(row.processStep), rowDisplay(row.characteristic), rowDisplay(row.specification), rowDisplay(row.method), rowDisplay(row.equipment), rowDisplay(row.sampleFrequency), rowDisplay(row.reactionPlan), rowDisplay(row.owner)]);
  if (key === "DVPR_ROWS") return (parseLocalTableRows(key, value) as DvprRow[]).map((row) => [rowDisplay(row.test), rowDisplay(row.applicability), rowDisplay(row.sampleCount), rowDisplay(row.acceptanceCriteria), rowDisplay(row.result), rowDisplay(row.evidence), rowDisplay(row.standardsReference)]);
  return (parseLocalTableRows(key, value) as BomCostRow[]).map((row) => [rowDisplay(row.itemNumber), rowDisplay(row.mpn), rowDisplay(row.manufacturer), rowDisplay(row.description), rowDisplay(row.package), rowDisplay(row.quantity), rowDisplay(row.leadTime), rowDisplay(row.unitCost), rowDisplay(row.currency), rowDisplay(row.aecqEvidence)]);
}
function tableText(key: LocalTableKey, value: string | null | undefined) { const rows = tableRowsForOutput(key, value); return rows.length ? rows.map((row) => `| ${row.join(" | ")} |`).join("\n") : tbc; }
export function quoteLineEstimate(row: QuoteLineRow) { if (validateLocalTableRows("QUOTE_LINE_ROWS", serializeLocalTableRows([row])).length || unknown(row.quantity) || unknown(row.unitPrice)) return tbc; return String(Number(row.quantity) * Number(row.unitPrice)); }
export function validateStructuredLocalEdits(kind: StructuredLifecycleTemplateKind, edits: Record<string, string | null>) {
  const preview = structuredLifecycleTemplatePreviews.find((item) => item.kind === kind);
  if (!preview) throw new Error("Unsupported structured lifecycle template.");
  for (const field of preview.editableFields.filter((item) => item.kind === "number")) numeric(edits[field.key] ?? "", field.label);
  for (const row of parseLocalTableRows("QUOTE_LINE_ROWS", edits.QUOTE_LINE_ROWS) as QuoteLineRow[]) { numeric(row.quantity, "Quote quantity"); numeric(row.unitPrice, "Quote unit price"); }
  for (const row of parseLocalTableRows("BOM_COST_ROWS", edits.BOM_COST_ROWS) as BomCostRow[]) { numeric(row.quantity, "BOM quantity"); numeric(row.unitCost, "BOM unit cost"); }
  for (const row of parseLocalTableRows("DFMEA_ROWS", edits.DFMEA_ROWS) as DfmeaRow[]) for (const [field, label] of [["severity", "Severity"], ["occurrence", "Occurrence"], ["detection", "Detection"]] as const) { const rating = row[field]; if (!unknown(rating) && !/^([1-9]|10)$/.test(rating.trim())) throw new Error(`${label} must be an integer from 1 to 10 or TBC.`); }
  for (const row of parseLocalTableRows("DVPR_ROWS", edits.DVPR_ROWS) as DvprRow[]) numeric(row.sampleCount, "DVP&R sample count");
  const tiers = parseLocalTableRows("VOLUME_TIER_ROWS", edits.VOLUME_TIER_ROWS) as VolumeTierRow[];
  for (const tier of tiers) { numeric(tier.minQuantity, "Tier minimum quantity"); numeric(tier.maxQuantity, "Tier maximum quantity"); numeric(tier.unitPrice, "Tier unit price"); if (!unknown(tier.minQuantity) && !unknown(tier.maxQuantity) && Number(tier.minQuantity) > Number(tier.maxQuantity)) throw new Error("Volume-tier minimum cannot exceed maximum."); }
  const complete = tiers.filter((tier) => !unknown(tier.minQuantity) && !unknown(tier.maxQuantity)).sort((a, b) => Number(a.minQuantity) - Number(b.minQuantity));
  for (let index = 1; index < complete.length; index += 1) if (Number(complete[index - 1].maxQuantity) >= Number(complete[index].minQuantity)) throw new Error("Volume tiers cannot overlap.");
}
export function mapMasterSpecificationSource(input: Omit<StructuredTemplateSource, "sourceFields"> & { specificationData: unknown }): StructuredTemplateSource { const data = input.specificationData && typeof input.specificationData === "object" && !Array.isArray(input.specificationData) ? input.specificationData as Record<string, unknown> : {}; return { ...input, sourceFields: { PROJECT_CODE: input.opportunityNumber, PROJECT_NAME: input.opportunityName, PROJECT_REVISION: `Master Specification rev ${input.versionNumber}`, CUSTOMER_NAME: input.customerName, MASTER_SPECIFICATION: `${input.specificationNumber} rev ${input.versionNumber}`, SOURCE_DOCUMENT: `${input.specificationNumber} revision ${input.versionNumber}`, REQUIREMENT_SUMMARY: text(data.requirementSummary), POWER_AND_UNITS: text(data.powerAndUnits), INTERFACES: text(data.interfaces), CONNECTIVITY_AND_GNSS: text(data.connectivityAndGnss), ENVIRONMENT_AND_IP: text(data.environmentAndIp), VOLUMES: text(data.volumes), REQUESTED_STANDARDS: text(data.requestedStandards), WORKSTREAMS: workstreams(data.workstreams) } }; }
export function renderStructuredLifecycleTemplatePreview(kind: StructuredLifecycleTemplateKind, source: StructuredTemplateSource | null, userEdits: Record<string, string | null> = {}) { validateStructuredLocalEdits(kind, userEdits); const preview = structuredLifecycleTemplatePreviews.find((item) => item.kind === kind); if (!preview) throw new Error("Unsupported structured lifecycle template."); const renderedEdits = { ...userEdits, QUOTE_LINE_ROWS: tableText("QUOTE_LINE_ROWS", userEdits.QUOTE_LINE_ROWS), VOLUME_TIER_ROWS: tableText("VOLUME_TIER_ROWS", userEdits.VOLUME_TIER_ROWS), BOM_COST_ROWS: tableText("BOM_COST_ROWS", userEdits.BOM_COST_ROWS), DFMEA_ROWS: tableText("DFMEA_ROWS", userEdits.DFMEA_ROWS), CONTROL_PLAN_ROWS: tableText("CONTROL_PLAN_ROWS", userEdits.CONTROL_PLAN_ROWS), DVPR_ROWS: tableText("DVPR_ROWS", userEdits.DVPR_ROWS) }; return renderLifecycleDocument({ ...preview.template, documentRevisionId: localRevision }, { ...preview.fields, ...(source?.sourceFields ?? {}), ...renderedEdits }); }
