import { describe, expect, it } from "vitest";
import { mapMasterSpecificationSource, renderStructuredLifecycleTemplatePreview, structuredLifecycleTemplatePreviews, validateStructuredLocalEdits } from "./lifecycle-structured-template-previews";

const source = mapMasterSpecificationSource({ opportunityId: "opportunity-id", opportunityNumber: "OPPORTUNITY-2026-0013", opportunityName: "Tracker <script>alert(1)</script>", customerId: "customer-id", customerName: "SAMPLE ONLY", specificationId: "specification-id", specificationNumber: "MASTER-2026-0001", versionId: "version-id", versionNumber: 1, changeSummary: "Initial intake", savedAt: "2026-10-05T18:37:27.589Z", specificationData: { requirementSummary: "24V tracker", powerAndUnits: "12/24V nominal input", interfaces: "CAN requested", connectivityAndGnss: "LTE/GNSS requested", environmentAndIp: "", volumes: "20 pilot units", requestedStandards: "", workstreams: ["HARDWARE", "FIRMWARE", "MECHANICAL"] } });

describe("structured lifecycle template previews", () => {
  it("defines six distinct safe document schemas", () => { expect(structuredLifecycleTemplatePreviews.map((template) => template.kind)).toEqual(["SOR", "CONTRACT_REVIEW", "PRS", "NDA", "COMMERCIAL_QUOTATION", "BOM_COST_TRACKER"]); expect(renderStructuredLifecycleTemplatePreview("NDA", source).content).toContain("UNCONFIRMED / TBC"); expect(renderStructuredLifecycleTemplatePreview("COMMERCIAL_QUOTATION", source).content).toContain("Unknown commercial values remain TBC, not zero"); expect(renderStructuredLifecycleTemplatePreview("BOM_COST_TRACKER", source).content).toContain("not a production BOM"); });
  it("keeps unknown source values visibly TBC and never infers authorization", () => { const contractReview = renderStructuredLifecycleTemplatePreview("CONTRACT_REVIEW", source).content; expect(contractReview).toContain("Customer authorization: NOT APPROVED / TBC (not inferred)."); expect(contractReview.match(/NOT APPROVED \/ TBC/g)?.length).toBeGreaterThanOrEqual(5); });
  it("substitutes user edits once and preserves HTML as literal text", () => { const rendered = renderStructuredLifecycleTemplatePreview("BOM_COST_TRACKER", source, { BOM_COST_ROWS: "<img src=x onerror=alert(1)> {{PROJECT_CODE}}", COST_RISK_NOTES: "TBC", LOCAL_COST_TOTAL: "TBC" }).content; expect(rendered).toContain("<img src=x onerror=alert(1)> {{PROJECT_CODE}}"); expect(rendered).not.toContain("<img src=x onerror=alert(1)> OPPORTUNITY-2026-0013"); });
  it("fails closed when a required editable field is missing", () => { expect(() => renderStructuredLifecycleTemplatePreview("PRS", source, { POWER_REQUIREMENT: null })).toThrow("POWER_REQUIREMENT"); });
  it("maps requested Master Specification values exactly without inventing technical values", () => { const rendered = renderStructuredLifecycleTemplatePreview("PRS", source).content; expect(rendered).toContain("12/24V nominal input"); expect(rendered).toContain("CAN requested"); expect(rendered).toContain("LTE/GNSS requested"); expect(rendered).toContain("20 pilot units"); expect(source.sourceFields.ENVIRONMENT_AND_IP).toBe("TBC"); expect(rendered).toContain("| PRS-006 | Components | TBC | TBC | TBC |"); });
  it("rejects invalid numeric commercial and cost entries while retaining explicit zero", () => { expect(() => validateStructuredLocalEdits("COMMERCIAL_QUOTATION", { NRE_AMOUNT: "unknown" })).toThrow("NRE amount"); expect(() => validateStructuredLocalEdits("BOM_COST_TRACKER", { LOCAL_COST_TOTAL: "-1" })).toThrow("Local estimated total"); expect(() => validateStructuredLocalEdits("COMMERCIAL_QUOTATION", { NRE_AMOUNT: "0", TOOLING_AMOUNT: "0" })).not.toThrow(); expect(renderStructuredLifecycleTemplatePreview("COMMERCIAL_QUOTATION", source).content).toContain("| NRE | TBC | TBC / not approved |"); });
  it("keeps BOM rows local and makes no part, price, grade or stock claim", () => { const content = renderStructuredLifecycleTemplatePreview("BOM_COST_TRACKER", source, { BOM_COST_ROWS: "ABC-1 | Example | local test row | TBC | TBC | TBC | TBC", COST_RISK_NOTES: "TBC", LOCAL_COST_TOTAL: "TBC" }).content; expect(content).toContain("ABC-1 | Example | local test row"); expect(content).toContain("not a production BOM, stock record or sourcing approval"); });
  it("keeps absent source values and malformed workstreams visibly TBC", () => { const incomplete = mapMasterSpecificationSource({ ...source, specificationData: { powerAndUnits: null, workstreams: ["HARDWARE", null] } }); expect(incomplete.sourceFields.POWER_AND_UNITS).toBe("TBC"); expect(incomplete.sourceFields.WORKSTREAMS).toBe("TBC"); expect(renderStructuredLifecycleTemplatePreview("PRS", incomplete).content).toContain("| PRS-006 | Components | TBC | TBC | TBC |"); });
  it("distinguishes a numeric zero source value from an unknown value", () => { const mapped = mapMasterSpecificationSource({ ...source, specificationData: { volumes: 0, requestedStandards: null } }); expect(mapped.sourceFields.VOLUMES).toBe("0"); expect(mapped.sourceFields.REQUESTED_STANDARDS).toBe("TBC"); });
  it("keeps different document schema fields type-specific", () => { expect(structuredLifecycleTemplatePreviews.find((item) => item.kind === "NDA")?.editableFields.map((field) => field.key)).toContain("GOVERNING_LAW"); expect(structuredLifecycleTemplatePreviews.find((item) => item.kind === "COMMERCIAL_QUOTATION")?.editableFields.map((field) => field.key)).toContain("VOLUME_TIER_ROWS"); expect(structuredLifecycleTemplatePreviews.find((item) => item.kind === "BOM_COST_TRACKER")?.editableFields.map((field) => field.key)).toContain("BOM_COST_ROWS"); });
  it("preserves local edits independently across document schemas", () => { const sor = renderStructuredLifecycleTemplatePreview("SOR", source, { OEM_REQUIREMENT_ROWS: "OEM-1 | tracker reporting | requested", SCOPE_STATEMENT: "TBC", ACCEPTANCE_CRITERIA: "TBC", CAN_TELEMETRY_NOTES: "TBC", PILOT_ROLLOUT_NOTES: "TBC", COMMERCIAL_SLA_WARRANTY_DELIVERY: "TBC" }).content; const nda = renderStructuredLifecycleTemplatePreview("NDA", source, { CONFIDENTIAL_SCOPE: "TBC", OBLIGATIONS: "TBC", IP_POSITION: "TBC", GOVERNING_LAW: "TBC" }).content; expect(sor).toContain("OEM-1 | tracker reporting | requested"); expect(nda).not.toContain("OEM-1 | tracker reporting | requested"); });
  it("renders every editable field into its controlled formatted source", () => { const edits = { POWER_REQUIREMENT: "12/24V accepted for local review", INTERFACE_REQUIREMENT: "CAN review", CONNECTIVITY_REQUIREMENT: "LTE review", MECHANICAL_REQUIREMENT: "TBC", FIRMWARE_REQUIREMENT: "TBC", VERIFICATION_METHOD: "Local verification proposal" }; const rendered = renderStructuredLifecycleTemplatePreview("PRS", source, edits).content; Object.values(edits).forEach((value) => expect(rendered).toContain(value)); });
});