import { supabase } from "@/integrations/supabase/client";

const sb = supabase as any;

export interface SalesCustomer { id: string; customer_code: string; legal_name: string; display_name: string | null; customer_type: string; industry: string | null; primary_email: string | null; primary_phone: string | null; status: string; account_owner_user_id: string | null; created_at: string; }
export interface SalesContact { id: string; customer_id: string; full_name: string; job_title: string | null; email: string | null; phone: string | null; mobile: string | null; is_primary: boolean; is_active: boolean; customer?: Pick<SalesCustomer, "id" | "legal_name" | "customer_code"> | null; }
export interface SalesEnquiry { id: string; enquiry_number: string; requirement_summary: string; source: string; enquiry_date: string; priority: string; status: string; application: string | null; estimated_volume: string | null; expected_timeline: string | null; next_action: string | null; next_action_date: string | null; customer?: Pick<SalesCustomer, "id" | "legal_name" | "customer_code"> | null; }
export interface SalesOpportunity { id: string; opportunity_number: string; name: string; stage: string; status: string; priority: string; application: string | null; product_type: string | null; nda_required: boolean; estimated_volume: string | null; target_timeline: string | null; next_action: string | null; next_action_date: string | null; customer?: Pick<SalesCustomer, "id" | "legal_name" | "customer_code"> | null; primary_contact?: Pick<SalesContact, "id" | "full_name" | "email"> | null; }
export interface MasterSpecificationSummary { id: string; opportunity_id: string; specification_number: string; title: string; status: string; current_version: number; }
export interface CustomerRequirement { id: string; requirement_number: string; opportunity_id: string; customer_id: string; title: string; status: string; current_revision: number; customer_reference: string | null; updated_at: string; opportunity?: Pick<SalesOpportunity, "id" | "name" | "opportunity_number"> | null; customer?: Pick<SalesCustomer, "id" | "legal_name" | "customer_code"> | null; }
export interface FeasibilityReview { id: string; requirement_id: string; department_id: string | null; status: string; findings: string | null; risks: string | null; reviewed_at: string | null; department?: { id: string; name: string; code: string | null } | null; }
export interface CommercialRecord { id: string; requirement_id: string; quotation_reference: string | null; currency: string; quoted_amount: number | null; status: string; customer_authorized_at: string | null; authorization_reference: string | null; }
export interface RequirementBaseline { id: string; requirement_id: string; baseline_number: string; revision_number: number; status: string; approved_at: string; }
export interface PortalAccess { id: string; customer_id: string; contact_id: string | null; access_token: string; label: string; expires_at: string | null; is_active: boolean; customer?: Pick<SalesCustomer, "id" | "legal_name"> | null; contact?: Pick<SalesContact, "id" | "full_name" | "email"> | null; }
export interface SalesHandover { id: string; baseline_id: string; project_id: string | null; status: string; handover_notes: string | null; initiated_at: string | null; baseline?: Pick<RequirementBaseline, "id" | "baseline_number" | "requirement_id"> | null; }

const CUSTOMER_SELECT = "id,customer_code,legal_name,display_name,customer_type,industry,primary_email,primary_phone,status,account_owner_user_id,created_at";

export async function fetchSalesOverview(): Promise<{ customers: SalesCustomer[]; contacts: SalesContact[]; enquiries: SalesEnquiry[]; opportunities: SalesOpportunity[]; masterSpecifications: MasterSpecificationSummary[]; requirements: CustomerRequirement[]; feasibilityReviews: FeasibilityReview[]; commercialRecords: CommercialRecord[]; baselines: RequirementBaseline[]; portalAccess: PortalAccess[]; handovers: SalesHandover[]; departments: Array<{ id: string; name: string; code: string | null }>; employees: Array<{ user_id: string; display_name: string | null; official_email: string | null }> }> {
  const [customers, contacts, enquiries, opportunities, masterSpecifications, requirements, feasibilityReviews, commercialRecords, baselines, portalAccess, handovers, departments, employees] = await Promise.all([
    sb.from("customers").select(CUSTOMER_SELECT).neq("status", "archived").order("created_at", { ascending: false }),
    sb.from("customer_contacts").select("id,customer_id,full_name,job_title,email,phone,mobile,is_primary,is_active,customer:customers(id,legal_name,customer_code)").eq("is_active", true).order("full_name"),
    sb.from("sales_enquiries").select("id,enquiry_number,requirement_summary,source,enquiry_date,priority,status,application,estimated_volume,expected_timeline,next_action,next_action_date,customer:customers(id,legal_name,customer_code)").neq("status", "archived").order("created_at", { ascending: false }),
    sb.from("sales_opportunities").select("id,opportunity_number,name,stage,status,priority,application,product_type,nda_required,estimated_volume,target_timeline,next_action,next_action_date,customer:customers(id,legal_name,customer_code),primary_contact:customer_contacts(id,full_name,email)").neq("status", "archived").order("updated_at", { ascending: false }),
    sb.from("master_specifications").select("id,opportunity_id,specification_number,title,status,current_version").order("updated_at", { ascending: false }),
    sb.from("customer_requirements").select("id,requirement_number,opportunity_id,customer_id,title,status,current_revision,customer_reference,updated_at,opportunity:sales_opportunities(id,name,opportunity_number),customer:customers(id,legal_name,customer_code)").neq("status", "archived").order("updated_at", { ascending: false }),
    sb.from("requirement_feasibility_reviews").select("id,requirement_id,department_id,status,findings,risks,reviewed_at,department:departments(id,name,code)").order("created_at", { ascending: false }),
    sb.from("sales_commercial_records").select("id,requirement_id,quotation_reference,currency,quoted_amount,status,customer_authorized_at,authorization_reference").order("updated_at", { ascending: false }),
    sb.from("requirement_baselines").select("id,requirement_id,baseline_number,revision_number,status,approved_at").order("approved_at", { ascending: false }),
    sb.from("customer_portal_access").select("id,customer_id,contact_id,access_token,label,expires_at,is_active,customer:customers(id,legal_name),contact:customer_contacts(id,full_name,email)").order("created_at", { ascending: false }),
    sb.from("sales_project_handovers").select("id,baseline_id,project_id,status,handover_notes,initiated_at,baseline:requirement_baselines(id,baseline_number,requirement_id)").order("created_at", { ascending: false }),
    sb.from("departments").select("id,name,code").eq("is_active", true).order("sort_order").order("name"),
    sb.from("employees").select("user_id,display_name,official_email").not("user_id", "is", null).eq("employment_status", "ACTIVE").order("display_name"),
  ]);
  for (const result of [customers, contacts, enquiries, opportunities, masterSpecifications, requirements, feasibilityReviews, commercialRecords, baselines, portalAccess, handovers, departments, employees]) if (result.error) throw result.error;
  return { customers: (customers.data ?? []) as SalesCustomer[], contacts: (contacts.data ?? []) as SalesContact[], enquiries: (enquiries.data ?? []) as SalesEnquiry[], opportunities: (opportunities.data ?? []) as SalesOpportunity[], masterSpecifications: (masterSpecifications.data ?? []) as MasterSpecificationSummary[], requirements: (requirements.data ?? []) as CustomerRequirement[], feasibilityReviews: (feasibilityReviews.data ?? []) as FeasibilityReview[], commercialRecords: (commercialRecords.data ?? []) as CommercialRecord[], baselines: (baselines.data ?? []) as RequirementBaseline[], portalAccess: (portalAccess.data ?? []) as PortalAccess[], handovers: (handovers.data ?? []) as SalesHandover[], departments: (departments.data ?? []) as Array<{ id: string; name: string; code: string | null }>, employees: (employees.data ?? []) as Array<{ user_id: string; display_name: string | null; official_email: string | null }> };
}