import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Plus, Trash2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
const sb = supabase as any;
export function ProjectTeamTab({ projectId }: { projectId: string }) {
 const qc = useQueryClient(); const [open, setOpen] = useState(false); const [employeeId, setEmployeeId] = useState(""); const [role, setRole] = useState("CONTRIBUTOR"); const [saving, setSaving] = useState(false);
 const { data: members = [], isLoading } = useQuery({queryKey:["project_team",projectId],queryFn:async()=>{const {data,error}=await sb.from("project_team_members").select("*, employee:employees(id, display_name, employee_code, job_title)").eq("project_id",projectId).order("created_at");if(error)throw error;return data??[];}});
 const { data: employees = [] } = useQuery({queryKey:["active_employees"],queryFn:async()=>{const {data,error}=await sb.from("employees").select("id, display_name, employee_code, job_title").eq("employment_status","ACTIVE").order("display_name");if(error)throw error;return data??[];}});
 const available = useMemo(()=>employees.filter((employee:any)=>!members.some((member:any)=>member.employee_id===employee.id)),[employees,members]); const refresh=()=>void qc.invalidateQueries({queryKey:["project_team",projectId]});
 const add=async()=>{if(!employeeId)return toast.error("Choose a team member");setSaving(true);const {error}=await sb.from("project_team_members").insert({project_id:projectId,employee_id:employeeId,project_role:role,discipline:role});setSaving(false);if(error)return toast.error(error.message);toast.success("Team member added");refresh();setOpen(false);};
 const remove=async(id:string)=>{if(!confirm("Remove this member from the project team?"))return;const {error}=await sb.from("project_team_members").delete().eq("id",id);if(error)return toast.error(error.message);toast.success("Team member removed");refresh();};
 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-base font-semibold">Project team</h2><p className="text-sm text-muted-foreground">People with project membership and context.</p></div><Button onClick={()=>{setEmployeeId("");setRole("CONTRIBUTOR");setOpen(true);}}><Plus className="h-4 w-4" />Add member</Button></div>{isLoading?<p className="text-sm text-muted-foreground">Loading…</p>:members.length===0?<Card className="p-8 text-center text-sm text-muted-foreground">No members assigned. Administrators can add the delivery team.</Card>:<div className="grid gap-2 md:grid-cols-2">{members.map((member:any)=><Card key={member.id} className="p-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="font-medium">{member.employee?.display_name ?? "Team member"}</p><p className="text-xs text-muted-foreground">{member.employee?.employee_code ?? "—"} · {member.employee?.job_title ?? member.project_role}</p><div className="mt-2 flex gap-2"><Badge variant="outline">{member.project_role}</Badge>{member.is_lead&&<Badge>Lead</Badge>}</div></div><Button variant="ghost" size="icon" aria-label="Remove member" title="Remove member" onClick={()=>remove(member.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></Card>)}</div>}<Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Add project member</DialogTitle><DialogDescription>Give an active employee a delivery role for this project.</DialogDescription></DialogHeader><div className="grid gap-3"><div><Label>Employee</Label><Select value={employeeId} onValueChange={setEmployeeId}><SelectTrigger><SelectValue placeholder="Select employee" /></SelectTrigger><SelectContent>{available.map((employee:any)=><SelectItem key={employee.id} value={employee.id}>{employee.display_name} · {employee.employee_code}</SelectItem>)}</SelectContent></Select></div><div><Label>Project role</Label><Input value={role} onChange={(event)=>setRole(event.target.value.toUpperCase())} placeholder="CONTRIBUTOR" /></div></div><DialogFooter><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={add} disabled={saving}>{saving?"Saving…":"Add member"}</Button></DialogFooter></DialogContent></Dialog></div>;
}
