import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { LoaderCircle } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { HrTrainingProgram } from "@/lib/hr";
import { assignTraining, createTrainingProgram } from "@/lib/hr.functions";

export function CreateTrainingProgramDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) { const create = useServerFn(createTrainingProgram); const queryClient = useQueryClient(); const [pending, setPending] = useState(false); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const form = new FormData(event.currentTarget); try { await create({ data: { title: String(form.get("title") ?? ""), description: String(form.get("description") ?? "").trim() || null, departmentId: null, deliveryMode: String(form.get("mode") ?? "self_paced") as "self_paced" | "instructor_led" | "external" | "on_the_job", isMandatory: form.get("mandatory") === "on" } }); toast.success("Learning program created"); onOpenChange(false); await queryClient.invalidateQueries({ queryKey: ["hr_training_admin"] }); } catch (error: any) { toast.error(error?.message ?? "Could not create learning program."); } finally { setPending(false); } } return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>New learning program</DialogTitle><DialogDescription>Set up a track that can be assigned to employees.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={submit}><div className="space-y-1.5"><Label htmlFor="program-title">Title</Label><Input id="program-title" name="title" required placeholder="Information security essentials" /></div><div className="space-y-1.5"><Label>Delivery</Label><Select name="mode" defaultValue="self_paced"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="self_paced">Self-paced</SelectItem><SelectItem value="instructor_led">Instructor-led</SelectItem><SelectItem value="external">External provider</SelectItem><SelectItem value="on_the_job">On the job</SelectItem></SelectContent></Select></div><Textarea name="description" rows={3} placeholder="Program description" /><div className="flex items-center gap-2"><Checkbox id="mandatory" name="mandatory" /><Label htmlFor="mandatory">Mandatory learning</Label></div><DialogFooter><Button disabled={pending}>{pending && <LoaderCircle className="size-4 animate-spin" />} Create program</Button></DialogFooter></form></DialogContent></Dialog>; }

export function AssignTrainingDialog({ program, employees, open, onOpenChange }: { program: HrTrainingProgram | null; employees: Array<{ id: string; display_name: string | null; official_email: string | null }>; open: boolean; onOpenChange: (open: boolean) => void }) { const assign = useServerFn(assignTraining); const queryClient = useQueryClient(); const [pending, setPending] = useState(false); if (!program) return null; const programId = program.id; async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const form = new FormData(event.currentTarget); try { await assign({ data: { programId, employeeId: String(form.get("employee") ?? ""), dueDate: String(form.get("dueDate") ?? "") || null } }); toast.success("Learning assigned"); onOpenChange(false); await queryClient.invalidateQueries({ queryKey: ["hr_training_admin"] }); } catch (error: any) { toast.error(error?.message ?? "Could not assign learning."); } finally { setPending(false); } } return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Assign learning</DialogTitle><DialogDescription>{program.title}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={submit}><div className="space-y-1.5"><Label>Employee</Label><Select name="employee" required><SelectTrigger><SelectValue placeholder="Select employee" /></SelectTrigger><SelectContent>{employees.map((employee) => <SelectItem key={employee.id} value={employee.id}>{employee.display_name ?? employee.official_email ?? "Employee"}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label htmlFor="due-date">Due date</Label><Input id="due-date" name="dueDate" type="date" /></div><DialogFooter><Button disabled={pending}>{pending && <LoaderCircle className="size-4 animate-spin" />} Assign</Button></DialogFooter></form></DialogContent></Dialog>; }
