import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, CircleAlert, Plus, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { reviewPhase6Record, savePhase6Record } from "@/lib/phase6.functions";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

const sb = supabase as any;
type ReviewType = "delivery_revision" | "rtv" | "payment_milestone";
export type OperationalConfig = { title: string; description: string; table: "po_shipments" | "po_delivery_revisions" | "supplier_ncrs" | "rtv_records" | "payment_milestones"; columns: { key: string; label: string }[]; inputs: { key: string; label: string; type?: "text" | "date" | "number" | "textarea" }[]; review?: { type: ReviewType; decisions: { value: string; label: string; tone?: "default" | "outline" | "destructive" }[] }; };
export function OperationalListPage({ config }: { config: OperationalConfig }) { const [open, setOpen] = useState(false); const [selected, setSelected] = useState<Record<string, unknown> | null>(null); const queryClient = useQueryClient(); const { data = [], isLoading } = useQuery({ queryKey: [config.table], queryFn: async () => { const { data, error } = await sb.from(config.table).select("*").order("created_at", { ascending: false }); if (error) throw error; return data as Record<string, unknown>[]; } }); const colSpan = config.columns.length + (config.review ? 1 : 0); return <div className="space-y-4 p-4 md:p-6"><div className="flex items-center gap-4"><div className="flex-1"><h1 className="text-xl font-semibold">{config.title}</h1><p className="text-sm text-muted-foreground">{config.description}</p></div><Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" /> New record</Button></div><Card className="overflow-x-auto"><Table><TableHeader><TableRow>{config.columns.map((column) => <TableHead key={column.key}>{column.label}</TableHead>)}{config.review && <TableHead>Decision</TableHead>}</TableRow></TableHeader><TableBody>{isLoading ? <TableRow><TableCell colSpan={colSpan} className="py-10 text-center">Loading…</TableCell></TableRow> : data.length === 0 ? <TableRow><TableCell colSpan={colSpan} className="py-10 text-center text-muted-foreground">No records yet</TableCell></TableRow> : data.map((record) => <TableRow key={String(record.id)}>{config.columns.map((column) => <TableCell key={column.key}>{String(record[column.key] ?? "—").replaceAll("_", " ")}</TableCell>)}{config.review && <TableCell><Button size="sm" variant="outline" onClick={() => setSelected(record)} disabled={Boolean(record.status && ["REJECTED", "CLOSED", "CANCELLED", "PAID"].includes(String(record.status)))}>Decide</Button></TableCell>}</TableRow>)}</TableBody></Table></Card><OperationalDialog config={config} open={open} onOpenChange={setOpen} onSaved={() => queryClient.invalidateQueries({ queryKey: [config.table] })} />{config.review && <ReviewDialog config={config} record={selected} onOpenChange={(value) => !value && setSelected(null)} onSaved={() => queryClient.invalidateQueries({ queryKey: [config.table] })} />}</div>; }
function OperationalDialog({ config, open, onOpenChange, onSaved }: { config: OperationalConfig; open: boolean; onOpenChange: (value: boolean) => void; onSaved: () => void }) { const [values, setValues] = useState<Record<string, string>>({}); const mutation = useMutation({ mutationFn: () => savePhase6Record({ data: { table: config.table, payload: Object.fromEntries(config.inputs.map((input) => [input.key, input.type === "number" ? Number(values[input.key] || 0) : values[input.key] || null])) } }), onSuccess: () => { toast.success("Record saved"); setValues({}); onSaved(); onOpenChange(false); }, onError: (error: Error) => toast.error(error.message) }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>New {config.title.toLowerCase().replace(/s$/, "")}</DialogTitle></DialogHeader><div className="grid gap-4 py-2">{config.inputs.map((input) => <div className="grid gap-2" key={input.key}><Label>{input.label}</Label>{input.type === "textarea" ? <Textarea value={values[input.key] ?? ""} onChange={(event) => setValues({ ...values, [input.key]: event.target.value })} /> : <Input type={input.type ?? "text"} value={values[input.key] ?? ""} onChange={(event) => setValues({ ...values, [input.key]: event.target.value })} />}</div>)}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={mutation.isPending} onClick={() => mutation.mutate()}>Save</Button></DialogFooter></DialogContent></Dialog>; }
function ReviewDialog({ config, record, onOpenChange, onSaved }: { config: OperationalConfig; record: Record<string, unknown> | null; onOpenChange: (value: boolean) => void; onSaved: () => void }) { const [notes, setNotes] = useState(""); const mutation = useMutation({ mutationFn: (decision: string) => reviewPhase6Record({ data: { recordType: config.review?.type ?? "payment_milestone", recordId: String(record?.id), decision, notes: notes || null } }), onSuccess: () => { toast.success("Decision recorded"); setNotes(""); onSaved(); onOpenChange(false); }, onError: (error: Error) => toast.error(error.message) }); if (!config.review) return null; return <Dialog open={Boolean(record)} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Record decision</DialogTitle></DialogHeader><div className="grid gap-2"><Label>Decision notes</Label><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Reason, exception, or follow-up" /></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>{config.review.decisions.map((decision) => <Button key={decision.value} variant={decision.tone ?? "default"} disabled={mutation.isPending} onClick={() => mutation.mutate(decision.value)}>{decision.value === "APPROVED" || decision.value === "ACCEPTED" || decision.value === "AUTHORIZED" ? <Check className="h-4 w-4" /> : decision.tone === "destructive" ? <X className="h-4 w-4" /> : <CircleAlert className="h-4 w-4" />}{decision.label}</Button>)}</DialogFooter></DialogContent></Dialog>; }