import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { savePhase9Record } from "@/lib/phase9.functions";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
const sb = supabase as any;
type Phase9Table = "qms_quality_objectives" | "qms_kpis" | "qms_kpi_formula_versions" | "qms_kpi_snapshots" | "qms_risks" | "qms_contingency_plans" | "qms_contingency_tests" | "qms_audits" | "qms_audit_findings" | "qms_capas" | "qms_improvements" | "qms_lessons_learned" | "qms_management_reviews" | "qms_retention_policies" | "customer_complaints" | "customer_warranty_claims" | "customer_returns" | "customer_field_failures" | "customer_satisfaction_surveys";
type InputConfig = { key: string; label: string; type?: "text" | "date" | "number" | "textarea"; options?: { value: string; label: string }[]; required?: boolean };
export type Phase9Config = { eyebrow: string; title: string; description: string; table: Phase9Table; columns: { key: string; label: string }[]; inputs: InputConfig[]; createLabel?: string };
export function Phase9ListPage({ config }: { config: Phase9Config }) { const [open, setOpen] = useState(false); const queryClient = useQueryClient(); const { data = [], isLoading } = useQuery({ queryKey: [config.table], queryFn: async () => { const { data, error } = await sb.from(config.table).select("*").order("created_at", { ascending: false }); if (error) throw error; return data as Record<string, unknown>[]; } }); return <section className="space-y-5 p-4 md:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">{config.eyebrow}</p><h1 className="mt-1 text-2xl font-semibold">{config.title}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{config.description}</p></div><Button onClick={() => setOpen(true)}><Plus />{config.createLabel ?? "New record"}</Button></div><Card className="overflow-x-auto"><Table><TableHeader><TableRow>{config.columns.map(c => <TableHead key={c.key}>{c.label}</TableHead>)}</TableRow></TableHeader><TableBody>{isLoading ? <TableRow><TableCell className="py-10 text-center" colSpan={config.columns.length}>Loading…</TableCell></TableRow> : data.length ? data.map(record => <TableRow key={String(record.id)}>{config.columns.map(column => <TableCell key={column.key}>{String(record[column.key] ?? "—").replaceAll("_", " ")}</TableCell>)}</TableRow>) : <TableRow><TableCell className="py-10 text-center text-muted-foreground" colSpan={config.columns.length}>No records yet.</TableCell></TableRow>}</TableBody></Table></Card><CreateDialog config={config} open={open} onOpenChange={setOpen} onSaved={() => queryClient.invalidateQueries({ queryKey: [config.table] })} /></section>; }
function CreateDialog({ config, open, onOpenChange, onSaved }: { config: Phase9Config; open: boolean; onOpenChange: (open: boolean) => void; onSaved: () => void }) { const [values, setValues] = useState<Record<string, string>>({}); const mutation = useMutation({ mutationFn: () => { const payload = Object.fromEntries(config.inputs.filter(i => values[i.key] !== undefined && values[i.key] !== "").map(i => [i.key, i.type === "number" ? Number(values[i.key]) : values[i.key]])); return savePhase9Record({ data: { table: config.table, payload } }); }, onSuccess: () => { toast.success("Record saved"); setValues({}); onSaved(); onOpenChange(false); }, onError: (error: Error) => toast.error(error.message) }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{config.createLabel ?? "New record"}</DialogTitle></DialogHeader><div className="grid gap-4 py-2">{config.inputs.map(input => <div className="grid gap-2" key={input.key}><Label>{input.label}{input.required ? " *" : ""}</Label>{input.type === "textarea" ? <Textarea value={values[input.key] ?? ""} onChange={e => setValues({ ...values, [input.key]: e.target.value })} /> : input.options ? <Select value={values[input.key] ?? ""} onValueChange={value => setValues({ ...values, [input.key]: value })}><SelectTrigger><SelectValue placeholder={`Select ${input.label.toLowerCase()}`} /></SelectTrigger><SelectContent>{input.options.map(option => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select> : <Input type={input.type ?? "text"} value={values[input.key] ?? ""} onChange={e => setValues({ ...values, [input.key]: e.target.value })} />}</div>)}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={mutation.isPending || config.inputs.some(i => i.required && !values[i.key]?.trim())} onClick={() => mutation.mutate()}>{mutation.isPending ? "Saving…" : "Save"}</Button></DialogFooter></DialogContent></Dialog>; }
