import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { toast } from "sonner";
import { FileCheck2, Plus } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { transitionDocumentControl } from "@/lib/document-control.functions";

const sb = supabase as any;
type Register = { id: string; drive_node_id: string; department_id: string; document_number: string; title: string; document_status: "DRAFT" | "IN_REVIEW" | "APPROVED" | "OBSOLETE"; controlled_version: number; approved_at: string | null; approval_note: string | null; reviewer_decision: string | null; released_at: string | null; drive_node?: { name: string } | null; department?: { name: string } | null };

export function DocumentControlRegister() {
  const client = useQueryClient();
  const [registering, setRegistering] = useState(false);
  const [selected, setSelected] = useState<Register | null>(null);
  const records = useQuery({ queryKey: ["document_control_registers"], queryFn: async () => { const { data, error } = await sb.from("document_control_registers").select("*, drive_node:drive_nodes(name), department:departments(name)").order("updated_at", { ascending: false }); if (error) throw error; return (data ?? []) as Register[]; } });
  const refresh = () => void client.invalidateQueries({ queryKey: ["document_control_registers"] });
  return <section className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-semibold"><FileCheck2 className="size-5 text-primary" /> Controlled document register</h2><p className="mt-1 text-sm text-muted-foreground">Department-controlled files, versions, approval status, and recorded decisions.</p></div><Button size="sm" onClick={() => setRegistering(true)}><Plus className="mr-1 size-4" /> Register document</Button></div><Card><CardContent className="p-0">{records.isLoading ? <p className="p-5 text-sm text-muted-foreground">Loading controlled documents…</p> : !records.data?.length ? <p className="p-5 text-sm text-muted-foreground">No controlled documents have been registered.</p> : <div className="overflow-auto"><table className="w-full text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr><th className="p-3">Document</th><th className="p-3">Department</th><th className="p-3">Version</th><th className="p-3">Status</th><th className="p-3" /></tr></thead><tbody>{records.data.map((record) => <tr key={record.id} className="border-t"><td className="p-3"><p className="font-medium">{record.title}</p><p className="text-xs text-muted-foreground">{record.document_number} · {record.drive_node?.name ?? "Drive file"}</p></td><td className="p-3">{record.department?.name ?? "—"}</td><td className="p-3">v{record.controlled_version}</td><td className="p-3"><Badge variant={record.document_status === "APPROVED" ? "secondary" : record.document_status === "OBSOLETE" ? "outline" : "default"}>{record.document_status.replaceAll("_", " ")}</Badge></td><td className="p-3 text-right"><Button size="sm" variant="outline" onClick={() => setSelected(record)}>History</Button></td></tr>)}</tbody></table></div>}</CardContent></Card><RegisterDialog open={registering} onOpenChange={setRegistering} onSaved={refresh} /><HistoryDialog record={selected} onClose={() => setSelected(null)} onSaved={refresh} /></section>;
}

function RegisterDialog({ open, onOpenChange, onSaved }: { open: boolean; onOpenChange: (value: boolean) => void; onSaved: () => void }) {
  const nodes = useQuery({ queryKey: ["controlled_drive_files"], queryFn: async () => { const { data, error } = await sb.from("drive_nodes").select("id,name,department_id, departments(name)").eq("node_type", "FILE").eq("is_trashed", false).order("name").limit(200); if (error) throw error; return data ?? []; } });
  const [nodeId, setNodeId] = useState(""); const [number, setNumber] = useState(""); const [title, setTitle] = useState(""); const [saving, setSaving] = useState(false);
  const save = async () => { const node = nodes.data?.find((item: any) => item.id === nodeId); if (!node || !number.trim() || !title.trim() || !node.department_id) return toast.error("Select a department file and complete the fields."); setSaving(true); const { error } = await sb.from("document_control_registers").insert({ drive_node_id: node.id, department_id: node.department_id, document_number: number.trim(), title: title.trim() }); setSaving(false); if (error) return toast.error(error.message); toast.success("Document registered"); onOpenChange(false); onSaved(); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Register controlled document</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Department file</Label><Select value={nodeId} onValueChange={setNodeId}><SelectTrigger><SelectValue placeholder="Select a file" /></SelectTrigger><SelectContent>{nodes.data?.map((node: any) => <SelectItem key={node.id} value={node.id}>{node.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Document number</Label><Input value={number} onChange={(event) => setNumber(event.target.value)} placeholder="QMS-001" /></div><div><Label>Controlled title</Label><Input value={title} onChange={(event) => setTitle(event.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={saving} onClick={() => void save()}>{saving ? "Registering…" : "Register"}</Button></DialogFooter></DialogContent></Dialog>;
}

function HistoryDialog({ record, onClose, onSaved }: { record: Register | null; onClose: () => void; onSaved: () => void }) {
  const transition = useServerFn(transitionDocumentControl);
  const [note, setNote] = useState(""); const [changeReason, setChangeReason] = useState(""); const [saving, setSaving] = useState(false);
  const events = useQuery({ queryKey: ["document_control_events", record?.id], queryFn: async () => { const { data, error } = await sb.from("document_control_events").select("*").eq("register_id", record?.id ?? "").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; }, enabled: Boolean(record) });
  const nextActions: Record<Register["document_status"], Array<{ label: string; action: "SUBMIT_REVIEW" | "REVIEW_APPROVE" | "REVIEW_REJECT" | "APPROVE" | "RELEASE" | "SUPERSEDE" }>> = {
    DRAFT: [{ label: "Submit for review", action: "SUBMIT_REVIEW" }],
    IN_REVIEW: [{ label: "Approve review", action: "REVIEW_APPROVE" }, { label: "Return to draft", action: "REVIEW_REJECT" }, { label: "Approve document", action: "APPROVE" }],
    APPROVED: [{ label: "Release document", action: "RELEASE" }, { label: "Supersede document", action: "SUPERSEDE" }],
    OBSOLETE: [],
  };
  const progress = async (action: "SUBMIT_REVIEW" | "REVIEW_APPROVE" | "REVIEW_REJECT" | "APPROVE" | "RELEASE" | "SUPERSEDE") => { if (!record) return; setSaving(true); try { await transition({ data: { registerId: record.id, action, expectedStatus: record.document_status, note: note.trim() || null, changeReason: changeReason.trim() || null, requestKey: crypto.randomUUID() } }); toast.success("Document control updated"); onSaved(); void events.refetch(); } catch (error: any) { toast.error(error?.message ?? "Could not update document control"); } finally { setSaving(false); } };
  if (!record) return null;
  return <Dialog open={Boolean(record)} onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{record.title}</DialogTitle></DialogHeader><div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div><Label>Status</Label><p className="mt-2 text-sm font-medium">{record.document_status.replaceAll("_", " ")}</p></div><div><Label>Release</Label><p className="mt-2 text-sm font-medium">{record.released_at ? new Date(record.released_at).toLocaleString() : "Not released"}</p></div></div><div><Label>Decision note</Label><Textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Recorded with the controlled action" /></div><div><Label>Change reason</Label><Textarea value={changeReason} onChange={(event) => setChangeReason(event.target.value)} placeholder="Required evidence for a complete audit trail" /></div><div><p className="mb-2 text-sm font-medium">Approval history</p>{events.data?.length ? <div className="space-y-2">{events.data.map((event: any) => <div key={event.id} className="border p-3 text-sm"><p className="font-medium">{event.event_type.replaceAll("_", " ")} · v{event.version ?? record.controlled_version}</p><p className="mt-1 text-xs text-muted-foreground">{event.note ?? "No note"} · {new Date(event.created_at).toLocaleString()}</p></div>)}</div> : <p className="text-sm text-muted-foreground">No recorded events yet.</p>}</div><Button asChild variant="outline" size="sm"><Link to="/drive" search={{ node: record.drive_node_id, department: record.department_id }}>Open source file</Link></Button></div><DialogFooter><Button variant="outline" onClick={onClose}>Close</Button>{nextActions[record.document_status].map((item) => <Button key={item.action} disabled={saving} onClick={() => void progress(item.action)}>{saving ? "Saving…" : item.label}</Button>)}</DialogFooter></DialogContent></Dialog>;
}