import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, ShieldAlert } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { fetchCanonicalDepartments } from "@/lib/tasks";
import { fetchLegacyDriveOwnershipPreflight } from "@/lib/legacy-drive-ownership-review";

export function LegacyDriveOwnershipReview() {
  const [proposedDepartmentId, setProposedDepartmentId] = useState("");
  const { data: departments = [] } = useQuery({ queryKey: ["active-departments"], queryFn: fetchCanonicalDepartments });
  const { data, isLoading, isError, refetch, isFetching } = useQuery({ queryKey: ["legacy-drive-ownership-preflight"], queryFn: fetchLegacyDriveOwnershipPreflight });
  const proposedDepartment = useMemo(() => departments.find((department) => department.id === proposedDepartmentId) ?? null, [departments, proposedDepartmentId]);

  return <section className="space-y-5">
    <div><h1 className="text-2xl font-semibold">Legacy Drive ownership review</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">Read-only preflight for legacy project folders. It reports RLS-visible facts only and never assigns, moves, repairs, or creates records.</p></div>
    <Card className="border-amber-500/40 bg-amber-500/5 p-4"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0" /><div><p className="text-sm font-medium">Backfill is not enabled</p><p className="mt-1 text-xs text-muted-foreground">An authorized Platform Owner must explicitly choose an owning department for a future reviewed transaction. This selection is a dry-run only; names, titles, BOMs, and descendants are never used to infer ownership.</p></div></div></Card>
    <div className="flex flex-wrap items-end gap-3"><label className="space-y-1"><span className="block text-xs font-medium text-muted-foreground">Proposed owner for dry-run</span><select aria-label="Proposed owning department" value={proposedDepartmentId} onChange={(event) => setProposedDepartmentId(event.target.value)} className="h-9 min-w-60 rounded-md border bg-background px-3 text-sm"><option value="">Choose explicitly — no selection</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label><Button variant="outline" disabled={isFetching} onClick={() => void refetch()}>{isFetching ? "Refreshing…" : "Refresh preflight"}</Button>{proposedDepartment && <p className="pb-2 text-xs text-muted-foreground">Dry-run selection: {proposedDepartment.name}. No transaction is available.</p>}</div>
    {isLoading ? <Card className="p-8 text-center text-muted-foreground">Loading RLS-visible project and Drive facts…</Card> : isError ? <Card className="border-destructive/40 bg-destructive/5 p-6 text-sm text-destructive">The preflight could not read the current RLS-visible Drive data.</Card> : data ? <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Affected projects", data.counts.affectedProjects], ["Unmapped projects", data.counts.unmappedProjects], ["Department mismatches", data.counts.descendantDepartmentMismatches], ["Storage gaps", data.counts.storageGaps], ["Revision gaps", data.counts.revisionGaps]].map(([label, count]) => <Card key={String(label)} className="p-4"><p className="text-2xl font-semibold">{count}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></Card>)}</div>
      <Card className="overflow-hidden"><div className="border-b p-4"><p className="font-medium">Project preflight</p><p className="mt-1 text-xs text-muted-foreground">Snapshot read {new Date(data.reviewedAt).toLocaleString()}. Counts reflect only records visible under the current session.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-muted/60 text-left text-xs text-muted-foreground"><tr><th className="p-3 font-medium">Project</th><th className="p-3 font-medium">Current owner</th><th className="p-3 font-medium">Drive nodes</th><th className="p-3 font-medium">Consistency</th><th className="p-3 font-medium">Source gaps</th></tr></thead><tbody>{data.projects.map((review) => { const issueCount = Number(review.requiresExplicitOwner) + review.descendantDepartmentMismatchCount + Number(review.projectDrivePointerGap) + Number(review.rootGap) + review.fileStorageGapCount + review.revisionGapCount; return <tr key={review.projectId} className="border-t align-top"><td className="p-3"><p className="font-medium">{review.projectLabel}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{review.projectId}</p></td><td className="p-3">{review.projectDepartmentId ?? <span className="text-destructive">Unmapped — explicit decision required</span>}</td><td className="p-3">{review.nodeCount}</td><td className="p-3 text-xs text-muted-foreground">{review.descendantDepartmentMismatchCount} mismatch · {review.descendantDepartmentMissingCount} missing · {review.rootGap ? "no root" : "root found"}{review.projectDrivePointerGap ? " · pointer gap" : ""}</td><td className="p-3"><span className={issueCount ? "inline-flex items-center gap-1 text-amber-700" : "inline-flex items-center gap-1 text-emerald-700"}>{issueCount ? <AlertTriangle className="h-3.5 w-3.5" /> : <CheckCircle2 className="h-3.5 w-3.5" />}{review.fileStorageGapCount} storage · {review.revisionGapCount} revision</span></td></tr>; })}</tbody></table></div></Card>
    </> : null}
  </section>;
}