import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { createExpense } from "@/lib/phase6.functions";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
export const Route = createFileRoute("/_authenticated/finance/expenses")({ component: ExpensesPage });
const sb = supabase as any;
function ExpensesPage() { const [open, setOpen] = useState(false); const qc = useQueryClient(); const { data: expenses = [] } = useQuery({ queryKey: ["quick_expenses"], queryFn: async () => { const { data, error } = await sb.from("quick_expenses").select("*").order("created_at", { ascending: false }); if (error) throw error; return data as any[]; } }); return <div className="space-y-4 p-4 md:p-6"><div className="flex items-center"><div className="flex-1"><h1 className="text-xl font-semibold">Expense requests</h1><p className="text-sm text-muted-foreground">Submit R&D and operational expenses for approval and finance processing.</p></div><Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" /> New expense</Button></div><Card className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Expense</TableHead><TableHead>Category</TableHead><TableHead>Description</TableHead><TableHead className="text-right">Amount</TableHead><TableHead>Status</TableHead><TableHead>Created</TableHead></TableRow></TableHeader><TableBody>{expenses.length === 0 ? <TableRow><TableCell colSpan={6} className="py-10 text-center text-muted-foreground">No expense requests yet</TableCell></TableRow> : expenses.map((expense) => <TableRow key={expense.id}><TableCell className="font-medium">{expense.expense_number}</TableCell><TableCell>{expense.category}</TableCell><TableCell>{expense.description}</TableCell><TableCell className="text-right">₹{Number(expense.amount).toLocaleString("en-IN")}</TableCell><TableCell>{expense.status}</TableCell><TableCell>{new Date(expense.created_at).toLocaleDateString("en-IN")}</TableCell></TableRow>)}</TableBody></Table></Card><ExpenseDialog open={open} onOpenChange={setOpen} onCreated={() => qc.invalidateQueries({ queryKey: ["quick_expenses"] })} /></div>; }
function ExpenseDialog({ open, onOpenChange, onCreated }: { open: boolean; onOpenChange: (value: boolean) => void; onCreated: () => void }) { const [category, setCategory] = useState(""); const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const mutation = useMutation({ mutationFn: () => createExpense({ data: { category, description, amount: Number(amount), is_rd: true } }), onSuccess: (expense) => { toast.success(`Expense ${expense.expense_number} submitted`); onCreated(); onOpenChange(false); setCategory(""); setDescription(""); setAmount(""); }, onError: (e: Error) => toast.error(e.message) }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>New R&D quick expense</DialogTitle></DialogHeader><div className="grid gap-4 py-2"><div className="grid gap-2"><Label>Category</Label><Input value={category} onChange={(e) => setCategory(e.target.value)} placeholder="Prototype material, travel, lab consumable…" /></div><div className="grid gap-2"><Label>Description</Label><Textarea value={description} onChange={(e) => setDescription(e.target.value)} /></div><div className="grid gap-2"><Label>Amount (INR, tax-inclusive)</Label><Input type="number" min="1" value={amount} onChange={(e) => setAmount(e.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={mutation.isPending} onClick={() => mutation.mutate()}>Submit expense</Button></DialogFooter></DialogContent></Dialog>; }