import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { CheckCircle2, ClipboardPlus, Plus } from "lucide-react";
import { PermissionGate } from "@/components/PermissionGate";
import { AddOnboardingItemDialog, CreateOnboardingPlanDialog } from "@/components/hr/OnboardingPlanDialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { fetchOnboardingOverview, type HrOnboardingPlan } from "@/lib/hr";
export const Route = createFileRoute("/_authenticated/hr/onboarding")({ head: () => ({ meta: [{ title: "Onboarding — SSM One" }, { name: "description", content: "Create reusable onboarding plans and clear joiner responsibilities." }, { property: "og:title", content: "Onboarding — SSM One" }, { property: "og:description", content: "Create reusable onboarding plans and clear joiner responsibilities." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: OnboardingPage });
function OnboardingPage() { const [planOpen, setPlanOpen] = useState(false); const [itemPlan, setItemPlan] = useState<HrOnboardingPlan | null>(null); const overview = useQuery({ queryKey: ["hr_onboarding"], queryFn: fetchOnboardingOverview }); return <PermissionGate permission="training.manage" fallback={<p className="text-sm text-muted-foreground">You do not have access to onboarding administration.</p>}><div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-medium text-primary">People operations</p><h1 className="mt-1 text-2xl font-semibold">Onboarding</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Build consistent joiner plans across HR, managers, IT, and employees.</p></div><Button onClick={() => setPlanOpen(true)}><Plus className="size-4" /> New plan</Button></div><div className="grid gap-4 xl:grid-cols-2">{overview.data?.map((plan) => <Card key={plan.id}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{plan.name}</CardTitle><CardDescription>{plan.description ?? "Reusable onboarding path"}</CardDescription></div><Badge variant="outline">{plan.items?.length ?? 0} steps</Badge></div></CardHeader><CardContent className="space-y-3">{plan.items?.map((item) => <div key={item.id} className="flex gap-3 border-l-2 border-primary/30 pl-3"><CheckCircle2 className="mt-0.5 size-4 text-primary" /><div><p className="text-sm font-medium">{item.title} {item.is_required && <span className="text-xs text-muted-foreground">Required</span>}</p><p className="text-xs text-muted-foreground">{item.owner_kind} · Day {item.due_offset_days}</p>{item.description && <p className="mt-1 text-xs text-muted-foreground">{item.description}</p>}</div></div>)}{!plan.items?.length && <p className="text-sm text-muted-foreground">No steps yet.</p>}<Button variant="outline" size="sm" onClick={() => setItemPlan(plan)}><ClipboardPlus className="size-4" /> Add step</Button></CardContent></Card>)}{!overview.data?.length && <p className="text-sm text-muted-foreground">No active onboarding plans yet.</p>}</div><CreateOnboardingPlanDialog open={planOpen} onOpenChange={setPlanOpen} /><AddOnboardingItemDialog plan={itemPlan} open={Boolean(itemPlan)} onOpenChange={(open) => { if (!open) setItemPlan(null); }} /></div></PermissionGate>; }
