import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, FileCheck2, Plus } from "lucide-react";
import { toast } from "sonner";
import { useServerFn } from "@tanstack/react-start";
import { PermissionGate } from "@/components/PermissionGate";
import { CreatePolicyDialog } from "@/components/hr/PolicyDialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { fetchPolicyOverview } from "@/lib/hr";
import { acknowledgePolicy } from "@/lib/hr.functions";
export const Route = createFileRoute("/_authenticated/hr/policies")({ head: () => ({ meta: [{ title: "Policies — SSM One" }, { name: "description", content: "Publish company policies and collect employee acknowledgements." }, { property: "og:title", content: "Policies — SSM One" }, { property: "og:description", content: "Publish company policies and collect employee acknowledgements." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: PoliciesPage });
function PoliciesPage() { const [createOpen, setCreateOpen] = useState(false); const policies = useQuery({ queryKey: ["hr_policies"], queryFn: fetchPolicyOverview }); const acknowledge = useServerFn(acknowledgePolicy); const queryClient = useQueryClient(); async function confirm(policyId: string) { try { await acknowledge({ data: { policyId } }); toast.success("Policy acknowledged"); await queryClient.invalidateQueries({ queryKey: ["hr_policies"] }); } catch (error: any) { toast.error(error?.message ?? "Could not acknowledge policy."); } } return <PermissionGate permission="hr.view" fallback={<p className="text-sm text-muted-foreground">You do not have access to policies.</p>}><div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-medium text-primary">People operations</p><h1 className="mt-1 text-2xl font-semibold">Policies</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Read active policies and retain an acknowledgement trail for every employee.</p></div><PermissionGate permission="training.manage"><Button onClick={() => setCreateOpen(true)}><Plus className="size-4" /> New policy</Button></PermissionGate></div><div className="grid gap-4 xl:grid-cols-2">{policies.data?.policies.map((policy) => { const done = policies.data?.acknowledgedPolicyIds.has(policy.id); return <Card key={policy.id}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{policy.title}</CardTitle><CardDescription>{policy.policy_code} · Version {policy.version}</CardDescription></div><Badge variant={policy.is_active ? "default" : "secondary"}>{policy.is_active ? "Published" : "Draft"}</Badge></div></CardHeader><CardContent className="space-y-4"><p className="min-h-10 text-sm text-muted-foreground">{policy.summary ?? "No summary has been provided."}</p>{policy.is_active && (done ? <Button variant="outline" disabled><Check className="size-4" /> Acknowledged</Button> : <Button onClick={() => void confirm(policy.id)}><FileCheck2 className="size-4" /> Acknowledge</Button>)}</CardContent></Card>; })}{!policies.data?.policies.length && <p className="text-sm text-muted-foreground">No policies have been published yet.</p>}</div><CreatePolicyDialog open={createOpen} onOpenChange={setCreateOpen} /></div></PermissionGate>; }
