import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Send } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { createPurchaseRequest } from "@/lib/phase6.functions";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/procurement/requests")({ component: PurchaseRequestsPage });
const sb = supabase as any;

function PurchaseRequestsPage() {
  const [open, setOpen] = useState(false); const qc = useQueryClient();
  const { data: requests = [] } = useQuery({ queryKey: ["purchase_requests"], queryFn: async () => { const { data, error } = await sb.from("purchase_requests").select("*, items:purchase_request_items(*)").order("created_at", { ascending: false }); if (error) throw error; return data as any[]; } });
  const active = useMemo(() => requests.filter((request) => !["CONVERTED", "CANCELLED", "REJECTED"].includes(request.status)).length, [requests]);
  return <div className="space-y-4 p-4 md:p-6"><div className="flex items-center gap-2"><div className="flex-1"><h1 className="text-xl font-semibold">Purchase requests</h1><p className="text-sm text-muted-foreground">Request material with traceable source, urgency, and line-level demand.</p></div><Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" /> New request</Button></div><div className="grid gap-3 sm:grid-cols-3"><Stat label="Active requests" value={active} /><Stat label="Awaiting review" value={requests.filter((r) => ["SUBMITTED", "UNDER_REVIEW"].includes(r.status)).length} /><Stat label="BOM shortage drafts" value={requests.filter((r) => r.source_type === "BOM_SHORTAGE").length} /></div><Card className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Request</TableHead><TableHead>Source</TableHead><TableHead>Status</TableHead><TableHead>Urgency</TableHead><TableHead>Required</TableHead><TableHead>Lines</TableHead><TableHead>Created</TableHead></TableRow></TableHeader><TableBody>{requests.length === 0 ? <TableRow><TableCell colSpan={7} className="py-10 text-center text-muted-foreground">No purchase requests yet</TableCell></TableRow> : requests.map((r) => <TableRow key={r.id}><TableCell className="font-medium">{r.request_number}</TableCell><TableCell>{r.source_type.replaceAll("_", " ")}</TableCell><TableCell><Badge variant={r.status === "REJECTED" ? "destructive" : "secondary"}>{r.status.replaceAll("_", " ")}</Badge></TableCell><TableCell>{r.urgency}</TableCell><TableCell>{r.required_date ?? "—"}</TableCell><TableCell>{r.items?.length ?? 0}</TableCell><TableCell>{new Date(r.created_at).toLocaleDateString("en-IN")}</TableCell></TableRow>)}</TableBody></Table></Card><RequestDialog open={open} onOpenChange={setOpen} onCreated={() => qc.invalidateQueries({ queryKey: ["purchase_requests"] })} /></div>;
}
function Stat({ label, value }: { label: string; value: number }) { return <Card className="p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></Card>; }
function RequestDialog({ open, onOpenChange, onCreated }: { open: boolean; onOpenChange: (value: boolean) => void; onCreated: () => void }) { const [mpn, setMpn] = useState(""); const [quantity, setQuantity] = useState("1"); const [requiredDate, setRequiredDate] = useState(""); const [urgency, setUrgency] = useState("NORMAL"); const [notes, setNotes] = useState(""); const mutation = useMutation({ mutationFn: () => createPurchaseRequest({ data: { source_type: "MANUAL", required_date: requiredDate || null, urgency, notes: notes || null, items: [{ mpn: mpn || null, required_quantity: Number(quantity), unit: "EA" }] } }), onSuccess: (request) => { toast.success(`Purchase request ${request.request_number} created`); onCreated(); onOpenChange(false); setMpn(""); setQuantity("1"); setNotes(""); }, onError: (error: Error) => toast.error(error.message) }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>New purchase request</DialogTitle><DialogDescription>Department and requester are resolved from your signed-in context.</DialogDescription></DialogHeader><div className="grid gap-4 py-2"><div className="grid gap-2"><Label>MPN or item description</Label><Input value={mpn} onChange={(e) => setMpn(e.target.value)} placeholder="e.g. STM32F103C8T6" /></div><div className="grid grid-cols-2 gap-3"><div className="grid gap-2"><Label>Required quantity</Label><Input type="number" min="1" value={quantity} onChange={(e) => setQuantity(e.target.value)} /></div><div className="grid gap-2"><Label>Required date</Label><Input type="date" value={requiredDate} onChange={(e) => setRequiredDate(e.target.value)} /></div></div><div className="grid gap-2"><Label>Urgency</Label><Select value={urgency} onValueChange={setUrgency}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["LOW", "NORMAL", "HIGH", "URGENT"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Notes</Label><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Need, source context, or impact if delayed" /></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={mutation.isPending} onClick={() => mutation.mutate()}><Send className="h-4 w-4" /> Submit request</Button></DialogFooter></DialogContent></Dialog>; }