import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, PackageCheck, ShieldAlert } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { decidePhase7FinishedGoodsRelease } from "@/lib/production.functions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/production/release")({ component: FinishedGoodsReleasePage, head: () => ({ meta: [{ title: "Finished goods release — SSM One" }, { name: "description", content: "Approval-controlled release of tested serialized finished goods." }, { property: "og:title", content: "Finished goods release — SSM One" }, { property: "og:description", content: "Release approved production units for packaging and dispatch." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }) });
const sb = supabase as any;
function FinishedGoodsReleasePage() {
  const qc = useQueryClient(); const [unit, setUnit] = useState<any | null>(null);
  const { data: units = [], isLoading } = useQuery({ queryKey: ["production_finished_goods_candidates"], queryFn: async () => { const { data, error } = await sb.from("production_units").select("*, work_order:work_orders(work_order_number,product_name), release:production_finished_goods_releases(status,packaging_reference,released_at)").in("unit_status", ["PASSED", "PACKED", "HOLD"]).order("completed_at", { ascending: false }); if (error) throw error; return data as any[]; } });
  const released = units.filter((item) => item.release?.status === "RELEASED").length;
  return <div className="space-y-4 p-4 md:p-6"><div><h1 className="text-xl font-semibold">Finished goods release</h1><p className="text-sm text-muted-foreground">Approve tested serialized units for packaging and controlled dispatch.</p></div><div className="grid gap-3 sm:grid-cols-3"><Metric icon={<CheckCircle2 />} label="Test passed" value={units.filter((item) => item.unit_status === "PASSED").length} /><Metric icon={<PackageCheck />} label="Released" value={released} /><Metric icon={<ShieldAlert />} label="Blocked" value={units.filter((item) => item.release?.status === "BLOCKED").length} /></div><Card className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Serial</TableHead><TableHead>Work order</TableHead><TableHead>Unit status</TableHead><TableHead>Release status</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{isLoading ? <TableRow><TableCell colSpan={5} className="py-10 text-center text-muted-foreground">Loading…</TableCell></TableRow> : units.length === 0 ? <TableRow><TableCell colSpan={5} className="py-10 text-center text-muted-foreground">No tested units are awaiting release.</TableCell></TableRow> : units.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.serial_number}</TableCell><TableCell>{item.work_order?.work_order_number ?? "—"}<div className="text-xs text-muted-foreground">{item.work_order?.product_name ?? ""}</div></TableCell><TableCell><Badge variant={item.unit_status === "HOLD" ? "destructive" : "secondary"}>{item.unit_status.replaceAll("_", " ")}</Badge></TableCell><TableCell><Badge variant={item.release?.status === "BLOCKED" ? "destructive" : "secondary"}>{item.release?.status ?? "PENDING"}</Badge></TableCell><TableCell><Button size="sm" disabled={item.unit_status !== "PASSED" && item.release?.status !== "RELEASED"} onClick={() => setUnit(item)}>{item.release?.status === "RELEASED" ? "Update" : "Review release"}</Button></TableCell></TableRow>)}</TableBody></Table></Card><ReleaseDialog unit={unit} onClose={() => setUnit(null)} onSaved={() => { qc.invalidateQueries({ queryKey: ["production_finished_goods_candidates"] }); setUnit(null); }} /></div>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <Card className="p-4"><div className="flex items-center gap-2 text-sm text-muted-foreground">{icon}{label}</div><p className="mt-1 text-2xl font-semibold">{value}</p></Card>; }
function ReleaseDialog({ unit, onClose, onSaved }: { unit: any | null; onClose: () => void; onSaved: () => void }) { const [reference, setReference] = useState(""); const [notes, setNotes] = useState(""); const mutation = useMutation({ mutationFn: () => decidePhase7FinishedGoodsRelease({ data: { unitId: unit.id, status: "RELEASED", packagingReference: reference || null, notes: notes || null } }), onSuccess: () => { toast.success("Finished goods released"); onSaved(); }, onError: (error: Error) => toast.error(error.message) }); return <Dialog open={Boolean(unit)} onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent><DialogHeader><DialogTitle>Release finished goods</DialogTitle><DialogDescription>{unit?.serial_number ?? ""}</DialogDescription></DialogHeader><div className="grid gap-4 py-2"><div className="grid gap-2"><Label>Packaging reference</Label><Input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Carton, label, or packing reference" /></div><div className="grid gap-2"><Label>Release note</Label><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Approval evidence or release conditions" /></div></div><DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={mutation.isPending} onClick={() => mutation.mutate()}>Release unit</Button></DialogFooter></DialogContent></Dialog>; }
