import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { updateIncomingInspection } from "@/lib/phase6.functions";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toast } from "sonner";
export const Route = createFileRoute("/_authenticated/quality/incoming")({ component: IncomingQualityPage });
const sb = supabase as any;
function IncomingQualityPage() { const qc = useQueryClient(); const { data: inspections = [] } = useQuery({ queryKey: ["incoming_inspections"], queryFn: async () => { const { data, error } = await sb.from("incoming_inspections").select("*, grn:goods_receipt_notes(grn_number), component:components(part_number)").order("created_at", { ascending: false }); if (error) throw error; return data as any[]; } }); const mutation = useMutation({ mutationFn: (input: { id: string; status: any }) => updateIncomingInspection({ data: input }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["incoming_inspections"] }); toast.success("Inspection decision recorded"); }, onError: (e: Error) => toast.error(e.message) }); return <div className="space-y-4 p-4 md:p-6"><div><h1 className="text-xl font-semibold">Incoming quality</h1><p className="text-sm text-muted-foreground">Accept, hold, or reject incoming material. Held items remain unavailable for normal issue.</p></div><Card className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Inspection</TableHead><TableHead>GRN</TableHead><TableHead>Part</TableHead><TableHead>Status</TableHead><TableHead>Decision</TableHead></TableRow></TableHeader><TableBody>{inspections.length === 0 ? <TableRow><TableCell colSpan={5} className="py-10 text-center text-muted-foreground">No incoming inspections are awaiting review.</TableCell></TableRow> : inspections.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.inspection_number ?? item.id.slice(0, 8)}</TableCell><TableCell>{item.grn?.grn_number ?? "—"}</TableCell><TableCell>{item.component?.part_number ?? "—"}</TableCell><TableCell><Badge variant={item.status === "REJECTED" ? "destructive" : "secondary"}>{item.status}</Badge></TableCell><TableCell className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={mutation.isPending} onClick={() => mutation.mutate({ id: item.id, status: "HOLD" })}>Hold</Button><Button size="sm" disabled={mutation.isPending} onClick={() => mutation.mutate({ id: item.id, status: "ACCEPTED" })}>Accept</Button><Button size="sm" variant="destructive" disabled={mutation.isPending} onClick={() => mutation.mutate({ id: item.id, status: "REJECTED" })}>Reject</Button></TableCell></TableRow>)}</TableBody></Table></Card></div>; }