/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationStatusRouteImport } from './routes/application-status'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as FileTokenRouteImport } from './routes/file.$token'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as AuthenticatedRdTeamRouteImport } from './routes/_authenticated/rd-team'
import { Route as AuthenticatedPcbRouteImport } from './routes/_authenticated/pcb'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated/locations'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDriveRouteImport } from './routes/_authenticated/drive'
import { Route as AuthenticatedBomRouteImport } from './routes/_authenticated/bom'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as ApiPublicDatasheetProxyRouteImport } from './routes/api/public/datasheet-proxy'
import { Route as AuthenticatedTasksDepartmentsRouteImport } from './routes/_authenticated/tasks.departments'
import { Route as AuthenticatedSettingsProjectsRouteImport } from './routes/_authenticated/settings.projects'
import { Route as AuthenticatedSettingsCategoriesRouteImport } from './routes/_authenticated/settings.categories'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedProcurementVendorsRouteImport } from './routes/_authenticated/procurement.vendors'
import { Route as AuthenticatedProcurementPendingRouteImport } from './routes/_authenticated/procurement.pending'
import { Route as AuthenticatedProcurementOrdersRouteImport } from './routes/_authenticated/procurement.orders'
import { Route as AuthenticatedProcurementInwardRouteImport } from './routes/_authenticated/procurement.inward'
import { Route as AuthenticatedHrRecruitmentRouteImport } from './routes/_authenticated/hr.recruitment'
import { Route as AuthenticatedHrOnboardingRouteImport } from './routes/_authenticated/hr.onboarding'
import { Route as AuthenticatedHrLeaveRouteImport } from './routes/_authenticated/hr.leave'
import { Route as AuthenticatedCategorySlugRouteImport } from './routes/_authenticated/category.$slug'
import { Route as ApiPublicHooksRefreshSupplierDataRouteImport } from './routes/api/public/hooks/refresh-supplier-data'

const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationStatusRoute = ApplicationStatusRouteImport.update({
  id: '/application-status',
  path: '/application-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FileTokenRoute = FileTokenRouteImport.update({
  id: '/file/$token',
  path: '/file/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareersRoute,
} as any)
const AuthenticatedRdTeamRoute = AuthenticatedRdTeamRouteImport.update({
  id: '/rd-team',
  path: '/rd-team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPcbRoute = AuthenticatedPcbRouteImport.update({
  id: '/pcb',
  path: '/pcb',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriveRoute = AuthenticatedDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBomRoute = AuthenticatedBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDatasheetProxyRoute = ApiPublicDatasheetProxyRouteImport.update({
  id: '/api/public/datasheet-proxy',
  path: '/api/public/datasheet-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksDepartmentsRoute =
  AuthenticatedTasksDepartmentsRouteImport.update({
    id: '/tasks/departments',
    path: '/tasks/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProjectsRoute =
  AuthenticatedSettingsProjectsRouteImport.update({
    id: '/settings/projects',
    path: '/settings/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCategoriesRoute =
  AuthenticatedSettingsCategoriesRouteImport.update({
    id: '/settings/categories',
    path: '/settings/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementVendorsRoute =
  AuthenticatedProcurementVendorsRouteImport.update({
    id: '/procurement/vendors',
    path: '/procurement/vendors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementPendingRoute =
  AuthenticatedProcurementPendingRouteImport.update({
    id: '/procurement/pending',
    path: '/procurement/pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementOrdersRoute =
  AuthenticatedProcurementOrdersRouteImport.update({
    id: '/procurement/orders',
    path: '/procurement/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementInwardRoute =
  AuthenticatedProcurementInwardRouteImport.update({
    id: '/procurement/inward',
    path: '/procurement/inward',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrRecruitmentRoute =
  AuthenticatedHrRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedHrOnboardingRoute =
  AuthenticatedHrOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedHrLeaveRoute = AuthenticatedHrLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)
const AuthenticatedCategorySlugRoute =
  AuthenticatedCategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksRefreshSupplierDataRoute =
  ApiPublicHooksRefreshSupplierDataRouteImport.update({
    id: '/api/public/hooks/refresh-supplier-data',
    path: '/api/public/hooks/refresh-supplier-data',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/application-status': typeof ApplicationStatusRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/bom': typeof AuthenticatedBomRoute
  '/drive': typeof AuthenticatedDriveRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/hr': typeof AuthenticatedHrRouteWithChildren
  '/locations': typeof AuthenticatedLocationsRoute
  '/pcb': typeof AuthenticatedPcbRoute
  '/rd-team': typeof AuthenticatedRdTeamRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/file/$token': typeof FileTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/hr/onboarding': typeof AuthenticatedHrOnboardingRoute
  '/hr/recruitment': typeof AuthenticatedHrRecruitmentRoute
  '/procurement/inward': typeof AuthenticatedProcurementInwardRoute
  '/procurement/orders': typeof AuthenticatedProcurementOrdersRoute
  '/procurement/pending': typeof AuthenticatedProcurementPendingRoute
  '/procurement/vendors': typeof AuthenticatedProcurementVendorsRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/tasks/departments': typeof AuthenticatedTasksDepartmentsRoute
  '/api/public/datasheet-proxy': typeof ApiPublicDatasheetProxyRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/api/public/hooks/refresh-supplier-data': typeof ApiPublicHooksRefreshSupplierDataRoute
}
export interface FileRoutesByTo {
  '/application-status': typeof ApplicationStatusRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/bom': typeof AuthenticatedBomRoute
  '/drive': typeof AuthenticatedDriveRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/hr': typeof AuthenticatedHrRouteWithChildren
  '/locations': typeof AuthenticatedLocationsRoute
  '/pcb': typeof AuthenticatedPcbRoute
  '/rd-team': typeof AuthenticatedRdTeamRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/file/$token': typeof FileTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/hr/onboarding': typeof AuthenticatedHrOnboardingRoute
  '/hr/recruitment': typeof AuthenticatedHrRecruitmentRoute
  '/procurement/inward': typeof AuthenticatedProcurementInwardRoute
  '/procurement/orders': typeof AuthenticatedProcurementOrdersRoute
  '/procurement/pending': typeof AuthenticatedProcurementPendingRoute
  '/procurement/vendors': typeof AuthenticatedProcurementVendorsRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/tasks/departments': typeof AuthenticatedTasksDepartmentsRoute
  '/api/public/datasheet-proxy': typeof ApiPublicDatasheetProxyRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/api/public/hooks/refresh-supplier-data': typeof ApiPublicHooksRefreshSupplierDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/application-status': typeof ApplicationStatusRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/bom': typeof AuthenticatedBomRoute
  '/_authenticated/drive': typeof AuthenticatedDriveRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/hr': typeof AuthenticatedHrRouteWithChildren
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/pcb': typeof AuthenticatedPcbRoute
  '/_authenticated/rd-team': typeof AuthenticatedRdTeamRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/file/$token': typeof FileTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/_authenticated/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/_authenticated/hr/onboarding': typeof AuthenticatedHrOnboardingRoute
  '/_authenticated/hr/recruitment': typeof AuthenticatedHrRecruitmentRoute
  '/_authenticated/procurement/inward': typeof AuthenticatedProcurementInwardRoute
  '/_authenticated/procurement/orders': typeof AuthenticatedProcurementOrdersRoute
  '/_authenticated/procurement/pending': typeof AuthenticatedProcurementPendingRoute
  '/_authenticated/procurement/vendors': typeof AuthenticatedProcurementVendorsRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/_authenticated/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/_authenticated/tasks/departments': typeof AuthenticatedTasksDepartmentsRoute
  '/api/public/datasheet-proxy': typeof ApiPublicDatasheetProxyRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/api/public/hooks/refresh-supplier-data': typeof ApiPublicHooksRefreshSupplierDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/application-status'
    | '/auth'
    | '/careers'
    | '/admin'
    | '/assignments'
    | '/bom'
    | '/drive'
    | '/history'
    | '/hr'
    | '/locations'
    | '/pcb'
    | '/rd-team'
    | '/careers/$slug'
    | '/file/$token'
    | '/share/$token'
    | '/category/$slug'
    | '/hr/leave'
    | '/hr/onboarding'
    | '/hr/recruitment'
    | '/procurement/inward'
    | '/procurement/orders'
    | '/procurement/pending'
    | '/procurement/vendors'
    | '/projects/$projectId'
    | '/settings/categories'
    | '/settings/projects'
    | '/tasks/departments'
    | '/api/public/datasheet-proxy'
    | '/projects/'
    | '/tasks/'
    | '/api/public/hooks/refresh-supplier-data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/application-status'
    | '/auth'
    | '/careers'
    | '/admin'
    | '/assignments'
    | '/bom'
    | '/drive'
    | '/history'
    | '/hr'
    | '/locations'
    | '/pcb'
    | '/rd-team'
    | '/careers/$slug'
    | '/file/$token'
    | '/share/$token'
    | '/'
    | '/category/$slug'
    | '/hr/leave'
    | '/hr/onboarding'
    | '/hr/recruitment'
    | '/procurement/inward'
    | '/procurement/orders'
    | '/procurement/pending'
    | '/procurement/vendors'
    | '/projects/$projectId'
    | '/settings/categories'
    | '/settings/projects'
    | '/tasks/departments'
    | '/api/public/datasheet-proxy'
    | '/projects'
    | '/tasks'
    | '/api/public/hooks/refresh-supplier-data'
  id:
    | '__root__'
    | '/_authenticated'
    | '/application-status'
    | '/auth'
    | '/careers'
    | '/_authenticated/admin'
    | '/_authenticated/assignments'
    | '/_authenticated/bom'
    | '/_authenticated/drive'
    | '/_authenticated/history'
    | '/_authenticated/hr'
    | '/_authenticated/locations'
    | '/_authenticated/pcb'
    | '/_authenticated/rd-team'
    | '/careers/$slug'
    | '/file/$token'
    | '/share/$token'
    | '/_authenticated/'
    | '/_authenticated/category/$slug'
    | '/_authenticated/hr/leave'
    | '/_authenticated/hr/onboarding'
    | '/_authenticated/hr/recruitment'
    | '/_authenticated/procurement/inward'
    | '/_authenticated/procurement/orders'
    | '/_authenticated/procurement/pending'
    | '/_authenticated/procurement/vendors'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/settings/categories'
    | '/_authenticated/settings/projects'
    | '/_authenticated/tasks/departments'
    | '/api/public/datasheet-proxy'
    | '/_authenticated/projects/'
    | '/_authenticated/tasks/'
    | '/api/public/hooks/refresh-supplier-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplicationStatusRoute: typeof ApplicationStatusRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRouteWithChildren
  FileTokenRoute: typeof FileTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiPublicDatasheetProxyRoute: typeof ApiPublicDatasheetProxyRoute
  ApiPublicHooksRefreshSupplierDataRoute: typeof ApiPublicHooksRefreshSupplierDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-status': {
      id: '/application-status'
      path: '/application-status'
      fullPath: '/application-status'
      preLoaderRoute: typeof ApplicationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/$token': {
      id: '/file/$token'
      path: '/file/$token'
      fullPath: '/file/$token'
      preLoaderRoute: typeof FileTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof CareersRoute
    }
    '/_authenticated/rd-team': {
      id: '/_authenticated/rd-team'
      path: '/rd-team'
      fullPath: '/rd-team'
      preLoaderRoute: typeof AuthenticatedRdTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pcb': {
      id: '/_authenticated/pcb'
      path: '/pcb'
      fullPath: '/pcb'
      preLoaderRoute: typeof AuthenticatedPcbRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive': {
      id: '/_authenticated/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof AuthenticatedDriveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bom': {
      id: '/_authenticated/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof AuthenticatedBomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/datasheet-proxy': {
      id: '/api/public/datasheet-proxy'
      path: '/api/public/datasheet-proxy'
      fullPath: '/api/public/datasheet-proxy'
      preLoaderRoute: typeof ApiPublicDatasheetProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks/departments': {
      id: '/_authenticated/tasks/departments'
      path: '/tasks/departments'
      fullPath: '/tasks/departments'
      preLoaderRoute: typeof AuthenticatedTasksDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/projects': {
      id: '/_authenticated/settings/projects'
      path: '/settings/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof AuthenticatedSettingsProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/categories': {
      id: '/_authenticated/settings/categories'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AuthenticatedSettingsCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/vendors': {
      id: '/_authenticated/procurement/vendors'
      path: '/procurement/vendors'
      fullPath: '/procurement/vendors'
      preLoaderRoute: typeof AuthenticatedProcurementVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/pending': {
      id: '/_authenticated/procurement/pending'
      path: '/procurement/pending'
      fullPath: '/procurement/pending'
      preLoaderRoute: typeof AuthenticatedProcurementPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/orders': {
      id: '/_authenticated/procurement/orders'
      path: '/procurement/orders'
      fullPath: '/procurement/orders'
      preLoaderRoute: typeof AuthenticatedProcurementOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/inward': {
      id: '/_authenticated/procurement/inward'
      path: '/procurement/inward'
      fullPath: '/procurement/inward'
      preLoaderRoute: typeof AuthenticatedProcurementInwardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/recruitment': {
      id: '/_authenticated/hr/recruitment'
      path: '/recruitment'
      fullPath: '/hr/recruitment'
      preLoaderRoute: typeof AuthenticatedHrRecruitmentRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/onboarding': {
      id: '/_authenticated/hr/onboarding'
      path: '/onboarding'
      fullPath: '/hr/onboarding'
      preLoaderRoute: typeof AuthenticatedHrOnboardingRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/leave': {
      id: '/_authenticated/hr/leave'
      path: '/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof AuthenticatedHrLeaveRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/category/$slug': {
      id: '/_authenticated/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof AuthenticatedCategorySlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/refresh-supplier-data': {
      id: '/api/public/hooks/refresh-supplier-data'
      path: '/api/public/hooks/refresh-supplier-data'
      fullPath: '/api/public/hooks/refresh-supplier-data'
      preLoaderRoute: typeof ApiPublicHooksRefreshSupplierDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedHrRouteChildren {
  AuthenticatedHrLeaveRoute: typeof AuthenticatedHrLeaveRoute
  AuthenticatedHrOnboardingRoute: typeof AuthenticatedHrOnboardingRoute
  AuthenticatedHrRecruitmentRoute: typeof AuthenticatedHrRecruitmentRoute
}

const AuthenticatedHrRouteChildren: AuthenticatedHrRouteChildren = {
  AuthenticatedHrLeaveRoute: AuthenticatedHrLeaveRoute,
  AuthenticatedHrOnboardingRoute: AuthenticatedHrOnboardingRoute,
  AuthenticatedHrRecruitmentRoute: AuthenticatedHrRecruitmentRoute,
}

const AuthenticatedHrRouteWithChildren = AuthenticatedHrRoute._addFileChildren(
  AuthenticatedHrRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedBomRoute: typeof AuthenticatedBomRoute
  AuthenticatedDriveRoute: typeof AuthenticatedDriveRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRouteWithChildren
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedPcbRoute: typeof AuthenticatedPcbRoute
  AuthenticatedRdTeamRoute: typeof AuthenticatedRdTeamRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCategorySlugRoute: typeof AuthenticatedCategorySlugRoute
  AuthenticatedProcurementInwardRoute: typeof AuthenticatedProcurementInwardRoute
  AuthenticatedProcurementOrdersRoute: typeof AuthenticatedProcurementOrdersRoute
  AuthenticatedProcurementPendingRoute: typeof AuthenticatedProcurementPendingRoute
  AuthenticatedProcurementVendorsRoute: typeof AuthenticatedProcurementVendorsRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedSettingsCategoriesRoute: typeof AuthenticatedSettingsCategoriesRoute
  AuthenticatedSettingsProjectsRoute: typeof AuthenticatedSettingsProjectsRoute
  AuthenticatedTasksDepartmentsRoute: typeof AuthenticatedTasksDepartmentsRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedBomRoute: AuthenticatedBomRoute,
  AuthenticatedDriveRoute: AuthenticatedDriveRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHrRoute: AuthenticatedHrRouteWithChildren,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedPcbRoute: AuthenticatedPcbRoute,
  AuthenticatedRdTeamRoute: AuthenticatedRdTeamRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCategorySlugRoute: AuthenticatedCategorySlugRoute,
  AuthenticatedProcurementInwardRoute: AuthenticatedProcurementInwardRoute,
  AuthenticatedProcurementOrdersRoute: AuthenticatedProcurementOrdersRoute,
  AuthenticatedProcurementPendingRoute: AuthenticatedProcurementPendingRoute,
  AuthenticatedProcurementVendorsRoute: AuthenticatedProcurementVendorsRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedSettingsCategoriesRoute: AuthenticatedSettingsCategoriesRoute,
  AuthenticatedSettingsProjectsRoute: AuthenticatedSettingsProjectsRoute,
  AuthenticatedTasksDepartmentsRoute: AuthenticatedTasksDepartmentsRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CareersRouteChildren {
  CareersSlugRoute: typeof CareersSlugRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersSlugRoute: CareersSlugRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplicationStatusRoute: ApplicationStatusRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRouteWithChildren,
  FileTokenRoute: FileTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiPublicDatasheetProxyRoute: ApiPublicDatasheetProxyRoute,
  ApiPublicHooksRefreshSupplierDataRoute:
    ApiPublicHooksRefreshSupplierDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
